// pages/week3-5.js — Weeks 3–5: Activation & Expansion — 20 days
import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Link from 'next/link'
import { useAuth } from '../lib/useAuth'
import { useProgress } from '../lib/useProgress'

const C = { green:'#3D5A3E', green2:'#2D4520', brown:'#6B4A2A', orange:'#C1581A', cream:'#FAF6F0', cream2:'#F2EBE0', text:'#2C1F14', muted:'#7A6A5A', border:'#E0D5C5', white:'#ffffff' }
const serif = "'Cormorant Garamond', serif"
const sans = "'Jost', sans-serif"
const weekColors = { 3: C.green, 4: C.brown, 5: C.orange }

const DAYS = [
  // ══════ WEEK 3: OPENING THE AJNA ══════
  {
    day: 15, title: 'Welcome to Activation', week: 3, theme: 'Crossing the Threshold', duration: '30 minutes',
    teaching: "You have arrived at the threshold.\n\nThe first two weeks were about building the ground. You established your practice. You learned the anatomy of the third eye. You cultivated stillness and breath. You began to hear yourself more clearly.\n\nNow we go deeper.\n\nWeeks 3 through 5 are called Activation and Expansion. This is the phase where the inner eye begins to genuinely open. Where what was theoretical becomes experiential. Where the practices move from building awareness to directly awakening it.\n\nThis phase asks more of you. More stillness. More honesty. More willingness to encounter the parts of yourself that have been waiting in the dark for your attention. The ancient initiates who entered temples of awakening in Egypt, India, and across Africa understood that the opening of the inner eye was not a comfortable process. It was a sacred one. And sacred things ask something real of us.\n\nThe word activation is used carefully here. It does not mean switching on a switch. It does not mean a sudden dramatic awakening where everything becomes clear in an instant. Activation means the deliberate, intentional deepening of the inner eye\u2019s capacity. It means moving from occasional glimpses of deeper perception to a more consistent, reliable relationship with your own intuitive knowing.\n\nIn the yogic tradition this process is called pratyahara \u2014 the withdrawal of the senses from the outer world in order to perceive the inner world more clearly. In the Sufi tradition it is called fana \u2014 the dissolving of the conditioned self. In the African sangoma tradition it is the period of thwasa \u2014 the calling and awakening of the healer\u2019s inner vision. The name changes. The essential process is the same.\n\nAs the inner eye begins to activate more fully, a range of experiences may arise. You may experience increased vividness in your dreams. You may notice heightened sensitivity to energy and emotional states around you. You may encounter old grief, anger, or fear surfacing \u2014 this is energy clearing, not breakdown. You may have moments of sudden, inexplicable knowing. All of these are welcome signs that the work is working.\n\nYou are ready. The foundation you built is exactly what this phase requires.",
    practice: "Before we begin the activation practices, make a conscious commitment to these three weeks.\n\nSit in your practice space. Ground yourself with 3 minutes of balanced breathing. Then take your journal and write this commitment in your own hand:\n\n\u201CFor the next twenty days I commit to showing up fully for my practice. I commit to honesty over comfort. I commit to remaining open even when what I encounter is uncomfortable. I commit to trusting the process even when I cannot see where it is leading. I understand that activation requires genuine surrender \u2014 not the surrender of my will, but the surrender of my resistance. I am willing to see what is real. I am willing to feel what is true. I am willing to become more of who I actually am. I am ready.\u201D\n\nSign it. Date it. Return to it whenever the work feels difficult.\n\nAfter writing your commitment, perform your full daily practice: grounding (2 min), protection (2 min), balanced breathing (3 min), third eye breath (5 min), silent meditation at the Ajna point (5 min).\n\nClose with 3 minutes of open awareness \u2014 simply receive whatever arises.",
    journalPrompt: "What are you most hoping to experience in these three weeks of activation? What are you most afraid might arise? Write both with complete honesty. Then write: what would change in your life if the inner eye were fully open and you fully trusted it?",
  },
  {
    day: 16, title: 'Deep Ajna Anatomy', week: 3, theme: 'Understanding What You Are Activating', duration: '35 minutes',
    teaching: "To activate something, it helps to understand what it actually is at a deeper level than we covered in Week 1.\n\nThe Ajna chakra is not merely a point on your forehead. It is a complex energy centre that serves as the command station for your entire subtle body. The word Ajna means both \u201Ccommand\u201D and \u201Cperceive\u201D in Sanskrit \u2014 it is the centre through which higher wisdom is both received and expressed.\n\nPhysically, the Ajna corresponds to the pineal gland, which produces melatonin and is exquisitely sensitive to light. But research has also shown that the pineal gland produces trace amounts of DMT (dimethyltryptamine) \u2014 the molecule associated with profound states of inner vision, near-death experiences, and the deepest meditative states. Your brain has a built-in capacity for transcendent perception. It is not something you need to import from outside.\n\nThe ancient Egyptians symbolised the pineal gland as the Eye of Horus \u2014 and when you look at the anatomical cross-section of the brain where the pineal gland sits, it maps precisely onto the Eye of Horus symbol. This was not coincidence. The Egyptians understood neuroanatomy at a level we are only now rediscovering.\n\nWhen the Ajna is functioning clearly, six qualities are present: Clarity \u2014 seeing situations as they truly are. Discernment \u2014 distinguishing truth from illusion. Imagination \u2014 genuine creative vision. Inner Vision \u2014 receiving images and symbols through inner sight. Telepathic Sensitivity \u2014 increased awareness of others\u2019 states. Cosmic Awareness \u2014 a felt connection to something larger.\n\nWhat blocks the Ajna? Rigidity of thinking. Constant overthinking that drowns out subtler signals. Unprocessed trauma that creates energetic blockages. Excessive screen time and artificial light. Fluoride accumulation. And perhaps most significantly: fear of the unknown. The inner eye will show you things your conditioned mind does not expect. If you are afraid of what you might see, you will unconsciously keep the eye closed. Courage is required.\n\nPhysical supports for the Ajna include: soft sun gazing at dawn or dusk, spending time in complete darkness, visualising indigo and violet light during meditation, using frankincense or sandalwood oil on the forehead, and above all \u2014 cultivating deep, consistent silence.",
    practice: "Today\u2019s practice has two parts.\n\nPart 1 \u2014 Darkness Meditation (15 minutes): Find the darkest room available. Sit with eyes open in complete darkness. Do not close your eyes. Allow the darkness to become alive rather than merely empty. After 5 minutes, bring your awareness to the Ajna point while keeping your eyes open in the dark. Notice any phosphenes (dots of light), colours, or patterns that appear. These are the visual cortex activating in the absence of external input \u2014 and they are also the first stirrings of inner sight. Stay for 15 minutes.\n\nPart 2 \u2014 Ajna Activation Breath (10 minutes): In your normal practice space, sit with eyes closed. Breathe directly into the third eye point \u2014 imagine each inhale flowing into the centre of your forehead. On each exhale, imagine the breath flowing outward through the third eye, carrying any fog or density with it. After 5 minutes of this, begin to visualise a small indigo flame at the Ajna point. Let it pulse and grow with each breath. Hold this for 5 more minutes.\n\nClose with 3 minutes of silent observation.",
    journalPrompt: "Of the six qualities of an open Ajna (clarity, discernment, imagination, inner vision, telepathic sensitivity, cosmic awareness), which feels most developed in you right now? Which feels most dormant? What do you sense is blocking it?",
  },
  {
    day: 17, title: 'The Central Activation Meditation', week: 3, theme: 'Core Third Eye Activation', duration: '45 minutes',
    teaching: "Today we do the work directly. This is the central activation meditation of the entire cohort.\n\nIt draws on techniques from the Tibetan Buddhist tradition of visualisation, the Hindu practice of trataka, the Sufi practice of muraqaba (watchful waiting), and the African tradition of entering the spirit body through sustained inner attention.\n\nSet aside 45 uninterrupted minutes. This is not a practice to rush. Find a space where you will not be disturbed. Sit comfortably with your spine upright. Dim the lights. You may light a candle or incense if that supports your entry into a meditative state.\n\nBefore you begin, place two or three drops of frankincense or sandalwood oil on your fingertip and gently touch the centre of your forehead. If you do not have these oils, simply place your fingertip at the centre of your forehead for thirty seconds with light, gentle pressure. This activates blood flow and awareness to the Ajna point.\n\nWhat happens in this meditation is between you and your inner world. Some people experience vivid colours, geometric patterns, or images. Others feel deep warmth, pressure, or pulsing at the third eye. Others experience a profound quality of stillness that feels different from ordinary rest. Others experience emotional release. All are valid. All are the work.\n\nThe Sufi masters called the receptive phase of this practice muraqaba \u2014 watchful waiting. It is not passive. It is an intensely alive form of attention that is receptive rather than seeking. Like a still pool that perfectly reflects whatever passes above it.",
    practice: "Part 1 \u2014 Arrival and Grounding (10 minutes): Begin with 4-7-8 breathing for five cycles. Then visualise roots growing from the base of your spine deep into the earth. Feel the earth\u2019s energy rising through these roots. You cannot safely expand upward without first being grounded downward. Stay here for the full 10 minutes.\n\nPart 2 \u2014 The Indigo Flame (15 minutes): With eyes closed, bring attention to the Ajna point. Breathe directly into this point. After 10 breaths, visualise a small point of deep indigo light there, no larger than a candle flame. With each inhale, let it gradually grow. It might pulse with your heartbeat. It might shift toward violet or deep blue. Allow it. If attention wanders, return to the flame. After 15 minutes it may have expanded to fill your entire forehead or even your entire head. Some people begin to see colours, geometric patterns, or images \u2014 natural phenomena of the awakening inner eye.\n\nPart 3 \u2014 Open Reception (15 minutes): Release the visualisation entirely. What remains is a quality of open, alive awareness at the Ajna point. Simply rest here. If images arise, observe. If words arrive, receive them. If feelings move through you, let them. If nothing appears, that is also fine. The activation is happening whether or not dramatic phenomena accompany it.\n\nPart 4 \u2014 Integration (5 minutes): Place both hands on your heart. Three slow breaths. Give thanks for whatever arose. Open your eyes very slowly. Sit for 2 full minutes before moving. Then write in your journal immediately.",
    journalPrompt: "What did you encounter in today\u2019s activation meditation? What images, feelings, sensations, or knowings arose? What surprised you most? What did the silence show you?",
  },
  {
    day: 18, title: 'Energy Clearing', week: 3, theme: 'Releasing What Blocks the Channel', duration: '40 minutes',
    teaching: "The inner eye is not simply a mental faculty. It operates through your entire energy system. And like any system, it can become blocked.\n\nEvery significant emotional experience leaves an energetic imprint in the body. This is not metaphor. Somatic therapists and trauma researchers have documented extensively how unprocessed emotional experiences are stored in the nervous system and body tissues. Peter Levine describes trauma as \u201Cfrozen energy\u201D \u2014 energy that was activated in response to a threatening experience and never completed its natural cycle of activation and release.\n\nThis stored energy sits directly in the channels through which the inner eye operates. Clearing it does not mean reliving every painful experience. It means giving the stored energy a pathway to move and release, gently, with your conscious support.\n\nIn the Yoruba tradition of West Africa, spiritual perception (known as \u201Coju inu\u201D \u2014 the inner eye) cannot function clearly while the practitioner carries unresolved emotional weight. Purification and clearing are considered prerequisites to genuine seeing, not optional extras. The same understanding exists in virtually every authentic tradition.\n\nToday\u2019s practice combines breathwork, sound, movement, and visualisation into a seven-layer clearing sequence. It is best done alone in a private space where you feel completely free to make sound and movement without self-consciousness.",
    practice: "The Seven-Layer Energy Clearing:\n\nLAYER 1 \u2014 BREATH ACTIVATION (5 min): Conscious connected breathing. Breathe continuously without pause between inhale and exhale. Belly first, then chest. Allow the breath to build energy.\n\nLAYER 2 \u2014 SOUND RELEASE (5 min): Continue breathing and add sound to the exhale. Start with a hum. Allow it to deepen into whatever wants to emerge \u2014 a sigh, a groan, a tone. Sound is one of the most powerful tools for moving stuck energy. Do not perform. Simply allow.\n\nLAYER 3 \u2014 MOVEMENT (5 min): Let your body move in response to the breath and sound. Shake your hands. Roll your shoulders. Sway. Stomp gently. Allow it to be organic, not choreographed. You are shaking loose what has been held.\n\nLAYER 4 \u2014 BODY SCAN WITH INTENTION (5 min): Come to stillness. Slowly scan from head to feet. At each area, ask: is there anything here ready to release? Breathe directly into areas of tightness or heaviness. Exhale and imagine that energy dispersing.\n\nLAYER 5 \u2014 FORGIVENESS BREATH (5 min): Bring to mind anyone you carry resentment toward. This is not about excusing what they did. It is about freeing yourself. With each exhale: \u201CI release this. I free myself. I reclaim this energy.\u201D\n\nLAYER 6 \u2014 SELF-COMPASSION (5 min): Turn the same attention to yourself. The ways you\u2019ve judged yourself harshly. Hands on heart. \u201CI forgive myself. I am learning. I am enough.\u201D\n\nLAYER 7 \u2014 SEALING WITH LIGHT (5 min): Visualise golden-white light entering through your crown, filling every space that has been cleared with warmth and vitality. Seal by pressing palms to the floor for 30 seconds.",
    journalPrompt: "What came up during the energy clearing? Where in your body did you feel the most resistance? What emotion was stored there? What shifted after the clearing?",
  },
  {
    day: 19, title: 'The Nightly Oracle', week: 3, theme: 'Advanced Dream Work', duration: '30 minutes + nightly practice',
    teaching: "Every night, without exception, your inner eye is active.\n\nWhile the conscious mind rests, the deeper layers of awareness speak freely in the language of the soul: images, symbols, emotions, archetypes, and stories that carry far more information than their surface appearance suggests.\n\nThe ancient Egyptians built entire temples dedicated to sacred dreaming. They called it sekhenu \u2014 the practice of receiving divine communication through the dream state. Seekers would undergo purification rituals, spend days in fasting and prayer, then lie down in sacred darkness to receive guidance. The dreams they received were considered among the most reliable forms of divine communication.\n\nDuring REM sleep, the brain produces theta waves \u2014 the same brain state associated with deep meditation and the most receptive states of inner vision. The prefrontal cortex (rational thinking) becomes significantly less active. The areas associated with emotion, imagery, memory, and pattern recognition become highly active. The inner eye operates more freely during dreams than at almost any other time.\n\nDreams can carry: guidance on real decisions, warnings about situations requiring attention, information about your psychological and spiritual state, creative solutions, contact with dimensions beyond ordinary consciousness, and premonitions of events that have not yet occurred.\n\nKey dream archetypes to recognise: The Shadow (your disowned qualities, often a threatening figure of the same gender), The Wise Elder (a guide offering counsel \u2014 take this figure seriously), The Child (your innocent, creative self calling you back to simplicity), and The Trickster (the disruptive figure forcing new perspectives, often appearing at transitions).",
    practice: "Establish your complete dream journaling system:\n\nTONIGHT BEFORE SLEEP:\n1. Place journal and pen within arm\u2019s reach of your bed.\n2. Write an intention: \u201CTonight I am open to receiving guidance through my dreams. I will remember what I am shown.\u201D\n3. Avoid alcohol, heavy food, and screens for 1 hour before bed.\n4. Perform 5 minutes of Ajna activation breath while lying in bed.\n5. Visualise indigo light at your third eye as you drift to sleep.\n\nTOMORROW MORNING (THE CRITICAL MOMENT):\n1. Do NOT move when you wake. Do NOT check your phone.\n2. Lie still. Let the dream come back to you.\n3. Reach for your journal and write immediately.\n4. Write in present tense: \u201CI am in a house\u201D not \u201CI was in a house.\u201D\n5. Record images, settings, characters, actions, emotional tone, symbols, colours, words spoken, and anything that felt strange or unexpected.\n\nWORKING WITH THE DREAM:\nAfter recording, sit quietly and ask: if this dream is a message from my deeper self, what is it saying? Trust your first response \u2014 the meaning that arrives before the thinking mind argues is usually most accurate.",
    journalPrompt: "Evening: What is one significant question you would like your dreams to answer tonight? Write it clearly.\n\nMorning: Record everything from your dreams. Then ask: what is this dream pointing toward in my waking life?",
  },
  {
    day: 20, title: 'The Full Energy Column', week: 3, theme: 'Chakra Awakening Meditation', duration: '45 minutes',
    teaching: "The third eye does not operate in isolation. It is one point in a complete system of seven energy centres running from the base of the spine to the crown of the head.\n\nWhen the entire system is balanced and flowing, the inner eye receives clear, unobstructed information. When lower centres are blocked, the third eye\u2019s signal is distorted. Think of it as a radio tower \u2014 the Ajna is the transmitter, but if the foundation is unstable, even the most powerful transmitter produces static.\n\nThe seven centres: Root (Muladhara) \u2014 safety, survival, groundedness. Colour: deep red. Sacral (Svadhisthana) \u2014 creativity, emotion, pleasure. Colour: warm orange. Solar Plexus (Manipura) \u2014 personal power, will, identity. Colour: bright yellow. Heart (Anahata) \u2014 love, compassion, connection. Colour: emerald green. Throat (Vishuddha) \u2014 expression, truth, authenticity. Colour: bright blue. Third Eye (Ajna) \u2014 intuition, inner vision, wisdom. Colour: deep indigo. Crown (Sahasrara) \u2014 spiritual connection, cosmic awareness. Colour: violet or white.\n\nEach blocked chakra has characteristic signs. A blocked root creates chronic anxiety. A blocked sacral creates emotional numbness. A blocked solar plexus creates chronic self-doubt. A blocked heart creates isolation and inability to give or receive love. A blocked throat creates fear of speaking truth. A blocked third eye creates mental fog. A blocked crown creates spiritual disconnection.\n\nWorking with the full chakra system is not a detour from third eye work. It is an essential part of it. The higher you wish to reach, the deeper your roots must go.",
    practice: "The Full Chakra Activation Meditation (45 minutes):\n\nLie down comfortably on your back. Close your eyes. Ten slow, deep breaths. Allow your body to become completely relaxed.\n\nYou will move through each chakra from base upward, spending 4-5 minutes at each centre.\n\nROOT: Visualise a deep red sphere at the base of your spine, warm and dense as earth. Feel your connection to the physical world, to the ground, to safety. Breathe into it until you feel genuinely grounded.\n\nSACRAL: See warm orange light below your navel, fluid and creative. Breathe into your creative centre. Release any shame about pleasure or desire.\n\nSOLAR PLEXUS: Bright yellow sun above your navel. Feel your personal power, your right to take up space, your inherent worth. Let it burn through self-doubt.\n\nHEART: Luminous emerald green radiating from your chest in all directions. Let your heart open gently like a flower. Breathe love in, breathe love out. Stay as long as needed.\n\nTHROAT: Clear bright blue at the centre of your throat. Feel the truth that lives in you that has not yet been spoken. Give it permission to exist.\n\nTHIRD EYE: Deep indigo flame at your forehead. You are home. Rest here for 5 full minutes.\n\nCROWN: Violet or white light opening like a lotus at the top of your head. Feel connection to something vast. Let the boundary between self and larger consciousness become permeable.\n\nINTEGRATION: Visualise a column of light from crown through all centres to the base, and from base into the earth. All centres aligned and glowing. Rest here 5 minutes in complete stillness.",
    journalPrompt: "Which chakra felt most blocked or resistant during today\u2019s practice? What domain of life does that centre govern? What does this tell you about where your growth edge currently is?",
  },
  {
    day: 21, title: 'Week 3 Integration', week: 3, theme: 'Rest, Reflection & Consolidation', duration: '20 minutes',
    teaching: "One week into activation. Pause here.\n\nThis week you worked directly with the Ajna centre. You did the central activation meditation. You cleared stored emotional energy. You began advanced dream work. You moved through the full chakra column.\n\nThis is significant work. The body and psyche need time to integrate what has been stirred and opened. Integration is not laziness \u2014 it is half of the transformation. Seeds need time in dark earth. Muscles grow during rest, not exercise. Consciousness works the same way.\n\nIf you feel slightly overwhelmed, that is appropriate. If you feel exhilarated, that is also appropriate. If you feel quiet and need days to process, that is perhaps most appropriate of all.\n\nA note on difficult experiences: some of you will have had uncomfortable, disorienting, or emotionally challenging experiences this week. Old grief surfacing. Unexpected anger. Disturbing dreams. Moments of confusion about who you are. This is not a sign something has gone wrong. This is the clearing in action. When you open the channel, everything sitting in the channel comes through on its way out. The uncomfortable experiences are part of the healing.\n\nIf the process feels genuinely overwhelming, reach out to David via WhatsApp. You are not meant to navigate this alone. The ancient initiates had guides. You do too.",
    practice: "Part 1 \u2014 Review (10 minutes): Read back through your journal entries from Days 15-20. Don\u2019t analyse \u2014 simply read. Notice what stands out now that didn\u2019t when you wrote it.\n\nPart 2 \u2014 Integration Questions: Sit with these in your journal today. Take your time.\n\nWhat has genuinely shifted in how I perceive the world since beginning this cohort?\n\nWhat has my dream life been showing me this week? Is there a consistent theme or symbol?\n\nWhere in my body do I feel the most open right now? Where do I still feel resistance?\n\nWhat truth has the inner eye shown me that the thinking mind has been resistant to accepting?\n\nWhat am I being called to release? What am I being called toward?\n\nPart 3 \u2014 Extended Rest: Nap, walk in nature, or sit in silence for as long as feels right. Today is about receiving, not doing.",
    journalPrompt: "Write a letter to your inner eye. Tell it what you have noticed this week. Tell it what you are still afraid to see. Ask it what it most wants you to know right now. Then sit in silence for 5 minutes and listen. Write whatever comes.",
  },
  // ══════ WEEK 4: DEVELOPING INTUITIVE GIFTS ══════
  {
    day: 22, title: 'Accessing the Subtle Realms', week: 4, theme: 'Expanding Beyond the Physical', duration: '40 minutes',
    teaching: "Welcome to Week 4. You have arrived at territory that few people enter deliberately.\n\nThe subtle realms are not a place you travel to. They are layers of reality that interpenetrate the physical world at every moment, invisible to ordinary perception but accessible to the awakened inner eye.\n\nThe Yoruba tradition speaks of the orun \u2014 the spiritual dimension existing alongside the aye, the physical world. The Hindu tradition describes multiple lokas, or planes of existence. The Tibetan Buddhist tradition maps multiple bardos, transitional states with characteristic phenomena. We approach these not as literal truth but as frameworks for navigating territory your own experience will confirm.\n\nFor practical purposes, we work with a four-layer model:\n\nTHE PHYSICAL LAYER: The world perceived by the five senses. Dense, material, measurable. The layer most people mistake for the totality of reality.\n\nTHE ETHERIC LAYER: The subtle energy field surrounding and interpenetrating the physical body. This is what healers and energy workers perceive. Many people first sense it as a slight luminosity or warmth around living bodies.\n\nTHE ASTRAL LAYER: Associated with the emotional body, the dream world, and archetypes. Time and space operate differently here. Symbolic communication is primary. This is what\u2019s accessed in deep meditation and vivid dreaming.\n\nTHE CAUSAL LAYER: The deepest layer accessible to human perception. Pure consciousness, absolute stillness, the ground of being from which all other layers emerge. This is what mystics call union with the divine.\n\nThe inner eye, as it develops, perceives across all four layers. Most people begin at the etheric and deepen toward the causal through sustained practice.",
    practice: "The Expanded Field Meditation (30 minutes):\n\nSit comfortably with eyes closed. Complete your grounding practice \u2014 5 minutes, roots into the earth, fully present.\n\nNow begin to expand outward from your body. As you inhale, feel your awareness extend about one foot beyond your skin in all directions. As you exhale, let it settle back slightly but not fully return.\n\nWith each breath cycle, allow your awareness to extend further. One foot. Two feet. Three feet. The edge of the room. Beyond the room.\n\nAs you expand, remain completely grounded. The roots go deeper as awareness expands outward. This is essential. Expansion without grounding is disorientation. Grounded expansion is true perception.\n\nAt each layer of expansion, notice: what do you sense here? You may notice warmth or aliveness beyond your physical skin. The emotional atmosphere of the space. The presence of nature if you are near it.\n\nDo not manufacture anything. Simply notice what is already there as your awareness becomes sensitive enough to perceive it.\n\nStay in this expanded state for 20 minutes. Then very slowly draw your awareness back to the physical body. Three grounding breaths. Press palms to the floor. Return fully before standing.",
    journalPrompt: "What did you sense in the expanded field? At what distance did you begin to perceive something beyond your physical body? What surprised you? Where did you feel most expanded and most resistant?",
  },
  {
    day: 23, title: 'Sensing Energy Fields', week: 4, theme: 'Aura Reading & Perception', duration: '35 minutes',
    teaching: "The human aura \u2014 the luminous energy field surrounding the physical body \u2014 has been described for thousands of years and photographed through Kirlian photography. Research in bioelectromagnetics and biophotons (light emitted by living cells) provides scientific grounding for what mystics have always known.\n\nThe aura is dynamic, constantly changing in response to thoughts, emotions, health, intention, and the presence of others. Learning to sense it is one of the most practically useful developments of the third eye.\n\nMost people sense auras before they see them \u2014 noticing warmth, coolness, expansion, or contraction around certain people. The visual element often develops later.\n\nAura colours carry information: Blue/indigo indicates calm, spirituality, clear communication. Green suggests healing, compassion, growth. Yellow indicates mental activity, optimism. Orange suggests creativity, emotional vitality. Red indicates strong physical energy, passion, or anger. White/gold around the crown indicates heightened spiritual awareness.\n\nImportant guidelines as this sensitivity develops: Always ground yourself before sensing others\u2019 fields. Maintain energetic boundaries \u2014 observe, don\u2019t merge. Never share unsolicited readings. Cleanse your field after working with others\u2019 energy \u2014 visualise water carrying away what isn\u2019t yours, or shake your hands as if shaking off water.",
    practice: "Exercise 1 \u2014 Sensing Your Own Aura (10 min): Hold your hands two feet apart, palms facing. Very slowly bring them together. At some point you\u2019ll feel resistance, warmth, tingling, or density between them \u2014 the edge of your etheric field. Play with this boundary. Push in, pull back. Get familiar with the sensation.\n\nExercise 2 \u2014 Seeing the Etheric Aura (15 min): Ask someone to stand against a plain neutral wall in soft light. Soften your gaze \u2014 don\u2019t stare hard. Look just to the side of the person. Allow your peripheral vision to work. After a minute or two, you may notice a slight luminosity or shimmer at the edges of their body \u2014 the etheric aura. With practice, this becomes more defined and colours may appear.\n\nIf you don\u2019t have a partner, practise on your own hand against a white wall. Soften your gaze and look just past the edges of your fingers. The etheric layer is usually the first visible layer.\n\nExercise 3 \u2014 Field Cleansing (5 min): After the exercises, stand and shake your hands vigorously. Visualise any energy that is not yours draining from your field into the earth. Take 3 grounding breaths.",
    journalPrompt: "What did you sense when working with energy fields today? What felt natural? What felt difficult? Did you perceive any visual phenomena around the edges of your body or another person\u2019s body?",
  },
  {
    day: 24, title: 'Lucid Dreaming', week: 4, theme: 'Conscious Awareness in the Dream State', duration: '30 minutes + nightly practice',
    teaching: "Lucid dreaming \u2014 becoming aware within a dream that you are dreaming \u2014 is one of the most significant developments in third eye work. In the lucid state, the inner eye operates with exceptional clarity. You can ask direct questions, navigate the dream landscape with intention, and encounter archetypal figures consciously.\n\nThe Tibetan Buddhist tradition developed an entire system called dream yoga around conscious dreaming. Indigenous dream traditions across Africa, the Americas, and Australia similarly treated it as sacred territory for healing and guidance.\n\nLucid dreaming occurs most commonly during later REM cycles, particularly the two hours before natural waking. The most reliable technique is MILD (Mnemonic Induction of Lucid Dreams) developed by Stephen LaBerge at Stanford: When you wake naturally around 4-5am, stay awake 15-20 minutes. Review your recent dream in detail. Set a clear intention: \u201CThe next time I am dreaming I will recognise that I am dreaming.\u201D Return to sleep.\n\nThe most effective daily practice is reality testing: throughout the day, randomly ask \u201CAm I dreaming right now?\u201D and actually check. Look at your hands \u2014 do they look normal? Look at text, look away, look back \u2014 does it change? In dreams, hands appear strange and text shifts. Because waking habits carry into dreams, you\u2019ll eventually ask this question inside a dream and get a different answer.\n\nOnce lucid: focus on physical sensations (touch ground, rub hands) to stabilise the dream. Then try: asking \u201CShow me what I need to see,\u201D meeting an inner guide by walking through a door with intention, or facing a shadow figure directly rather than fleeing \u2014 asking \u201CWho are you? What do you represent?\u201D",
    practice: "Daytime Practice \u2014 Reality Testing: Set 5 reminders on your phone throughout the day. Each time, stop and genuinely ask: \u201CAm I dreaming?\u201D Look at your hands. Look at text, away, and back. Try to push a finger through your opposite palm (in dreams, it goes through). Do this with genuine curiosity each time, not mechanically.\n\nEvening Practice \u2014 MILD Setup: Before bed, review your dream journal from the past few nights. Notice recurring elements. As you lie down, repeat to yourself: \u201CThe next time I am dreaming, I will recognise that I am dreaming.\u201D Visualise yourself in a recent dream, but this time becoming lucid within it. See yourself realising you are dreaming. Hold this visualisation as you drift off.\n\nIf You Wake in the Night: If you wake naturally between 3-5am, stay awake for 15-20 minutes. Read your dream journal. Repeat the MILD intention. Return to sleep. This dramatically increases the chance of a lucid dream in your next REM cycle.\n\nContinue your regular morning dream journaling.",
    journalPrompt: "Have you ever experienced a lucid dream? Describe it if so. If not, what would you do with full lucid awareness in the dream state? What question would you ask? What would you want to see?",
  },
  {
    day: 25, title: 'Intuitive Reading', week: 4, theme: 'Sensing the Unseen in People & Objects', duration: '40 minutes',
    teaching: "Today we move the inner eye from inner perception to outer perception \u2014 using your developed sensitivity to receive information about people, places, and situations beyond what ordinary observation reveals.\n\nThe word \u201Cpsychic\u201D comes from the Greek psyche, meaning soul. It is not supernatural. It is the natural extension of the inner eye\u2019s perceptual range when the filtering systems of the conditioned mind relax.\n\nPsychometry is the practice of receiving impressions from objects. Physical objects absorb emotional and energetic imprints of the people and events associated with them. The activated inner eye can read these imprints through direct contact.\n\nRemote viewing is perceiving places, objects, or events beyond ordinary sensory range. The US military studied this extensively in Project Stargate, running from the 1970s to 1990s \u2014 significant enough that the programme operated for over two decades.\n\nThe ethics of developed perception are crucial: You do not read people without their permission. Your perceptions are filtered through your own psychology \u2014 hold them humbly. The development of intuitive perception is for service, not personal power. The ethical practitioner only offers what is asked for, and always with the caveat that they may be wrong.",
    practice: "Exercise 1 \u2014 Psychometry (15 min): Ask someone to give you a personal object (watch, ring, stone) they\u2019ve had for some time. Don\u2019t ask anything about it. Hold it in your non-dominant hand. Close your eyes. Three grounding breaths. Open your inner awareness to whatever arises \u2014 images, feelings, colours, names, places, emotions, physical sensations. Don\u2019t edit or dismiss anything. After 5 minutes, share everything. Ask the person if anything resonates. You may be surprised.\n\nExercise 2 \u2014 Remote Viewing (15 min): Ask someone to choose a location, photograph it, and write a number code on paper. You receive only the code. In a relaxed meditative state, allow impressions to arise. Indoors or outdoors? Water? Urban or natural? Colours? Shapes? Emotional quality? Write everything. Then compare with the photograph.\n\nExercise 3 \u2014 Field Cleansing (5 min): After any intuitive work, ground yourself thoroughly. Shake your hands. Visualise any absorbed energy returning to the earth. Take 3 deep breaths.\n\nThe point is not perfect accuracy from the start. You are training the perceptual muscle and learning to distinguish genuine inner perception from mental noise.",
    journalPrompt: "What arose during the psychometry and remote viewing exercises? What felt like genuine perception versus mental guessing? How do you relate to the idea of intuitive perception beyond ordinary senses? What excites you? What raises questions?",
  },
  {
    day: 26, title: 'Sound, Frequency & the Inner Eye', week: 4, theme: 'Vibrational Activation', duration: '40 minutes',
    teaching: "Sound is one of the oldest technologies for activating the inner eye. Before written language, before organised religion, human beings used sound, voice, rhythm, and vibration to enter expanded consciousness.\n\nThe Vedic tradition built an entire science around sacred sound (mantra). Southern African cultures used the mbira, drum, and communal song to enter spiritual perception. Aboriginal Australians used the didgeridoo and songlines \u2014 vibrational maps of the landscape. Modern neuroscience confirms what these traditions knew: sound directly alters brainwave states.\n\nBinaural beats are particularly relevant: two slightly different frequencies played in each ear cause the brain to produce a third frequency. For third eye work, theta binaural beats (6-8 Hz) are most supportive \u2014 the brainwave state associated with deep intuition, dream consciousness, and inner vision.\n\nEach chakra has a seed sound (bija mantra): Root: LAM. Sacral: VAM. Solar Plexus: RAM. Heart: YAM. Throat: HAM. Third Eye: OM (AUM). Crown: Silence or a high-pitched tone.\n\nWhen you chant AUM, the three syllables each vibrate in a different part of the body: A (aah) in the chest, U (ooh) in the throat, M (mmm) in the head and third eye. The silence after AUM represents turiya \u2014 pure awareness beyond all states. This is the state the third eye perceives from.",
    practice: "Full Chakra Toning Sequence (25 min):\n\nSit comfortably with eyes closed. Begin at the root chakra. Tone each seed sound for 2 minutes, feeling the vibration in the corresponding body area. Move upward through each centre:\n\nROOT: LAAAAAMMMMM \u2014 feel vibration at the base of spine\nSACRAL: VAAAAAMMMMM \u2014 feel vibration below navel\nSOLAR PLEXUS: RAAAAAMMMMM \u2014 feel vibration at stomach\nHEART: YAAAAAMMMMM \u2014 feel vibration at chest centre\nTHROAT: HAAAAAMMMMM \u2014 feel vibration at throat\nTHIRD EYE: OOOOOMMMMM \u2014 feel vibration at forehead (spend 5 minutes here)\nCROWN: Soft, high-pitched hum or silence \u2014 feel vibration at crown\n\nAfter completing all seven centres, sit in complete silence for 5 minutes. The contrast between vibrational activation and silence is itself a powerful tool for opening the inner ear.\n\nOptional: Search for \u201Ctheta binaural beats third eye\u201D on any music platform. Listen through headphones during your meditation for at least 20 minutes for the entrainment effect.",
    journalPrompt: "How did your body respond to the toning? Which chakra sound produced the strongest sensation? What did the silence after toning feel like compared to ordinary silence?",
  },
  {
    day: 27, title: 'The Akashic Field', week: 4, theme: 'Memory of Everything', duration: '35 minutes',
    teaching: "Across spiritual traditions there is a concept of a field of consciousness in which all information, all events, and all possibilities are permanently recorded and accessible to the awakened inner eye.\n\nThe Hindu tradition calls it the Akasha \u2014 from Sanskrit for \u201Cether\u201D \u2014 a cosmic library containing the complete history of every soul. Physicist Ervin Laszlo described the quantum vacuum as an information field where all events leave permanent traces \u2014 the A-field. Biologist Rupert Sheldrake proposed morphic resonance \u2014 a collective memory field transcending individual space and time.\n\nWhether through ancient spirituality or cutting-edge physics, the idea is the same: there is a field of information available to the awakened inner eye that extends far beyond individual experience.\n\nThe field is not elsewhere. It is here, interpenetrating everything. It is not ordinarily perceptible because the noise of ordinary consciousness is too loud for its subtle frequencies. The deep silence you have cultivated since Week 1 is the prerequisite.\n\nIn this silence, the inner eye sometimes accesses what feels like knowing things you could not logically know \u2014 a sudden understanding of a historical event\u2019s deeper meaning, a sense of connection to people you\u2019ve never met, an impression that feels like memory but belongs to a larger story than your biography.",
    practice: "The Akashic Meditation (25 minutes):\n\nThis is among the most advanced practices in the cohort. Approach with patience. The first times you may simply experience deep stillness \u2014 that is enough. Access deepens over time.\n\nSit comfortably. Complete your full grounding practice. Activate the indigo flame at the Ajna for 5 minutes.\n\nNow imagine you are in a vast, dark, star-filled space. Not outer space physically, but a space of pure consciousness. Infinite. Silent. Alive.\n\nAllow a significant question to arise. Not a small personal question, but something that genuinely matters at the deepest level. About your life\u2019s purpose. About the nature of a relationship. About a pattern whose origins you don\u2019t understand.\n\nHold the question lightly in the space. Do not seek an answer with your thinking mind. Simply hold the question and allow the field to respond.\n\nYou may receive an image, a feeling, a sense of knowing, a memory that doesn\u2019t feel like your own, a word or phrase, a vision. Remain receptive for 15-20 minutes.\n\nReturn to ordinary awareness very slowly. Record everything immediately \u2014 the meaning of Akashic impressions often unfolds over days.",
    journalPrompt: "What question did you bring to the Akashic meditation? What, if anything, came in response? How did the space feel? How do you relate to the concept of an information field beyond individual consciousness?",
  },
  {
    day: 28, title: 'Week 4 Integration', week: 4, theme: 'Deep Rest & Consolidation', duration: '20 minutes',
    teaching: "Two weeks into activation. Four weeks into the cohort.\n\nYou have covered extraordinary territory: Ajna activation, energy clearing, advanced dream work, subtle realms, aura sensing, sound and vibration, the Akashic field.\n\nIf you feel slightly overwhelmed, that is appropriate. If you feel exhilarated, also appropriate. If you feel quiet and need days to process, perhaps most appropriate of all.\n\nThis is genuine inner work. It leaves a mark. Not necessarily on your outer life yet, though that will come. But on the inner landscape. On the quality of your awareness. On the relationship between you and the deeper parts of yourself.\n\nRest today. The quiet consolidation of what has been opened is as important as any active practice.\n\nPreparing for Week 5: The final week of Activation works with integration and your specific intuitive gifts. We bring together everything that has been activated and begin weaving it into a coherent, lived spiritual practice. We also identify your primary intuitive channel \u2014 the specific way your inner eye speaks most naturally. Not everyone\u2019s eye opens the same way.",
    practice: "Part 1 \u2014 Integration Questions (15 min): Write freely in response to these. Do not rush.\n\nWhat is the most significant inner experience I have had in this cohort so far?\n\nHow has my relationship with my dreams changed?\n\nWhat have I sensed about energy fields that surprised me?\n\nWhere am I still most resistant to opening? What am I protecting?\n\nWhat is the most honest thing I can say about who I am becoming?\n\nWhat would I tell someone about to begin this cohort?\n\nPart 2 \u2014 Extended Rest: Do something nourishing today. Walk in nature. Take a bath. Cook a good meal. Sleep early. Let the work settle.",
    journalPrompt: "Four weeks in \u2014 who are you becoming? Write about this without modesty and without inflation. Simply honestly. Who is emerging through this practice?",
  },
  // ══════ WEEK 5: DISCOVERING YOUR UNIQUE CHANNEL ══════
  {
    day: 29, title: 'Your Unique Intuitive Gift', week: 5, theme: 'Identifying Your Primary Channel', duration: '35 minutes',
    teaching: "Welcome to the final week of the Activation phase.\n\nOne of the most important discoveries you can make is identifying your primary intuitive modality \u2014 the specific channel through which your inner eye speaks most naturally. Just as people have different learning styles, people have different intuitive channels. Understanding yours gives you a home base you can develop to a high level of reliability.\n\nThe four primary channels are:\n\nCLAIRVOYANCE (Clear Seeing): Receiving information as images, colours, symbols, or scenes in the inner visual field. Clairvoyants think in pictures. Their dreams are vivid and visual. They may literally see auras. Signs: you think in images rather than words, you have detailed dreams, you get visual impressions that turn out accurate.\n\nCLAIRSENTIENCE (Clear Feeling): Receiving information through physical and emotional sensations. Clairsentients feel others\u2019 emotions as their own. They sense room atmospheres immediately. Signs: you\u2019re highly empathic, significantly affected by others\u2019 emotional states, you feel guidance as gut tightening, chest warmth, or skin tingling.\n\nCLAIRAUDIENCE (Clear Hearing): Receiving information through inner sounds, words, music, or voices. May hear your name called in silence. Receive guidance as a clear inner voice distinct from ordinary thinking. Signs: strongly affected by music, sometimes hear words from somewhere other than your thinking, sensitive to tone of voice.\n\nCLAIRCOGNIZANCE (Clear Knowing): Receiving information as sudden, complete knowing without any image, feeling, or sound. Simply knowing things without being able to explain how. This gift is often hardest to trust precisely because there\u2019s no accompanying sensation. Signs: you often know things without explaining how, you have strong convictions that prove accurate, your intuition arrives as certainty.\n\nTo identify your primary gift, ask: When I\u2019ve received accurate intuitive guidance in the past, how did it come? In meditation, what type of experience arises most naturally? Which channel do I most tend to dismiss? That last question is particularly revealing \u2014 the channel you dismiss most is often your actual primary gift.",
    practice: "Part 1 \u2014 Self-Assessment (10 min): In your journal, reflect on each of the four channels. Rate how strongly each resonates with your experience on a scale of 1-10. Write specific examples from your life that demonstrate each channel.\n\nPart 2 \u2014 Direct Testing (20 min):\n\nFor Clairvoyance: Close your eyes and ask to be shown an image that carries meaning for you right now. Wait. What appears?\n\nFor Clairsentience: Bring to mind someone you care about. What do you feel in your body? What emotion arises? What do you sense they need right now?\n\nFor Clairaudience: In deep silence, ask: \u201CWhat do I most need to hear today?\u201D Listen with your inner hearing. What word, phrase, or sound arrives?\n\nFor Claircognizance: Write a question at the top of your journal page. Without thinking, write the answer that arrives in the first 5 seconds. Don\u2019t evaluate. Just write.\n\nNotice which exercise felt most natural and produced the clearest response. That is likely your primary channel.\n\nWrite your conclusion: \u201CMy primary intuitive channel appears to be...\u201D",
    journalPrompt: "Which of the four channels feels most natural to you? Which have you been dismissing or doubting? What would change in your life if you fully trusted your primary intuitive gift?",
  },
  {
    day: 30, title: 'Developing Your Primary Gift', week: 5, theme: 'Targeted Channel Practice', duration: '40 minutes',
    teaching: "Now that you\u2019ve identified your primary intuitive channel, today we develop it with targeted practice.\n\nThe principle is the same as any skill: specific, focused, consistent practice aimed directly at the faculty you are developing produces faster results than general practice alone. A musician who knows they are primarily a pianist practises piano. They also study theory and listen widely. But the piano is their instrument.\n\nYour primary intuitive channel is your instrument. The targeted practices below strengthen it directly.\n\nRemember: you are not limited to one channel. Over time, all four develop. But having a strong primary channel gives you a reliable foundation from which to expand. It is the channel you return to when you need clear, trustworthy guidance.",
    practice: "Perform your full daily practice (grounding, protection, breathwork, Ajna activation). Then do the targeted exercise for YOUR primary channel:\n\nFOR CLAIRVOYANTS (20 min): Sit with eyes closed. After Ajna activation, place awareness on the dark screen behind closed eyes. Intentionally see a simple shape \u2014 a circle. Hold it for 30 seconds. Release. See a triangle. Hold. Release. Now allow an image to arise spontaneously. Notice its detail, colour, movement. Ask it: \u201CWhat do you represent?\u201D Alternate between directed visualisation and spontaneous reception for 20 minutes.\n\nFOR CLAIRSENTIENTS (20 min): Ground fully. Bring awareness entirely into your body. Amplify sensitivity by holding a loved one in awareness \u2014 notice what you feel. Warmth? Pressure? Emotion? A sensation in a specific body area? Ask your body: \u201CWhat is this person most needing right now?\u201D Let the answer come as felt sense, not thought. Repeat with 2-3 different people.\n\nFOR CLAIRAUDIENTS (20 min): Sit in deep silence. Activate the Ajna. Bring awareness to the inner auditory space behind ordinary thinking. Ask: \u201CWhat do I most need to hear today?\u201D Listen. Not with ears but with inner hearing. A word may arise. A phrase. A name. A sound. Write everything, including what seems too quiet to count. Clairaudient messages often arrive as if your own thoughts \u2014 the difference is a quality of clarity and otherness that becomes unmistakeable with practice.\n\nFOR CLAIRCOGNIZANTS (20 min): Write 10 questions at the top of 10 journal pages \u2014 real questions from your life. For each, without thinking, write the answer in the first 5 seconds. Don\u2019t consider or evaluate. Simply write the first knowing. Then review all 10. Notice how many immediate knowings carry genuine insight.",
    journalPrompt: "How did the targeted practice feel? What arose? What became clearer about how your particular inner eye speaks? What surprised you about the accuracy or quality of what came through?",
  },
  {
    day: 31, title: 'Spiritual Protection Mastery', week: 5, theme: 'Energetic Boundaries for the Activated Eye', duration: '30 minutes',
    teaching: "As the inner eye opens and sensitivity increases, spiritual protection and energetic boundaries become essential.\n\nThis is not rooted in fear but in wisdom. Just as you lock your door not from paranoia but from self-care, energetic boundaries are part of living wisely in an expanded perceptual world.\n\nSigns your boundaries need attention: feeling significantly heavier or depleted after time with certain people; absorbing others\u2019 emotions and losing track of your own; chronic tiredness not explained by physical activity; overwhelm in crowded spaces; saying yes when you mean no because you feel the other\u2019s disappointment; losing your sense of self in relationships.\n\nEvery tradition that works with expanded consciousness has protection practices. The Christian tradition speaks of \u201Cthe full armour of God.\u201D The Zulu sangoma tradition uses specific herbs, prayers, and rituals. Tibetan Buddhism uses visualisations and mantras. The underlying principle is the same: consciously maintaining the integrity of your energy field while remaining open to the wider world.",
    practice: "Three Core Protection Practices \u2014 learn all three, use daily:\n\nPRACTICE 1 \u2014 THE LIGHT SHIELD (before going out): Close your eyes. Three deep breaths. Visualise a sphere of brilliant white or golden light surrounding your body, about one foot beyond your skin. This sphere is fully permeable to love, truth, and genuine connection. It is impermeable to energy that is not yours. Hold for 30 seconds. Carry it with you.\n\nPRACTICE 2 \u2014 CORD CUTTING (end of each day): Sit quietly. Call to mind anyone you interacted with today. Visualise the energetic cords connecting you to each person. These cords are not your relationships \u2014 they are residue of the interaction. Imagine cutting each cord cleanly at your boundary. You\u2019re releasing energetic attachment, not the relationship. Then visualise any energy that is not yours draining from your field into the earth to be neutralised.\n\nPRACTICE 3 \u2014 THE DAILY SEALING (each morning): After your practice, visualise your crown chakra as a lotus you can open or close. During practice: fully open. During ordinary life: half-open. During chaotic environments: mostly closed, maintaining just a thread of connection. This conscious regulation of permeability is one of the most important skills of the developed intuitive.\n\nPractise all three today and incorporate them into your daily routine from this point forward.",
    journalPrompt: "Where in your life do you most notice the impact of insufficient energetic boundaries? With whom? In what situations? What would change if those boundaries were strong and clear?",
  },
  {
    day: 32, title: 'Integration Into Daily Life', week: 5, theme: 'From Practice to Living', duration: '35 minutes',
    teaching: "The activation phase is nearly complete. The most important question of the journey: how do you take what has been activated and bring it into the actual texture of your daily life?\n\nMany people do profound inner work, have genuine experiences, then return to ordinary life and within two weeks everything fades. The insights disappear. The practices slip. This does not have to happen. But preventing it requires intentional design.\n\nIntegration happens at three levels:\n\nTHE PRACTICE LEVEL: You maintain your daily practice. Not from rigid rule-following but because you\u2019ve experienced what it opens. Minimum daily: 10-15 minutes breath and stillness, Ajna activation 3x/week, dream recording every morning, evening reflection.\n\nTHE PERCEPTION LEVEL: Bringing inner eye awareness into ordinary moments. While washing dishes. In conversation. Walking down the street. The practice is: pause, breathe, notice. What is this person actually feeling? What is the deeper quality of this moment? What is being asked of me here?\n\nTHE BEHAVIOUR LEVEL: This is what ultimately matters. Does the awakened inner eye change how you live? Does clarity translate into different choices? Does expanded perception lead to more compassionate, authentic, purposeful action? Where is your inner eye showing you something that requires change? What relationship needs an honest conversation? What habit no longer serves your growth? What calling has been quiet but consistent?\n\nPeople who have genuinely integrated an active inner eye are not recognisable by spiritual performance. They are recognisable by being genuinely present. Honest without being harsh. Responsive rather than reactive. Purposeful from within. Compassionate as a natural consequence of truly perceiving others.",
    practice: "Part 1 \u2014 The Integration Audit (15 min): In your journal, answer honestly:\n\nPractice Level: How consistent has my daily practice been? What threatens it? What would make it sustainable for life?\n\nPerception Level: In the past week, when did I use my inner eye outside of formal practice? When did I miss an opportunity to?\n\nBehaviour Level: What is my inner eye asking me to change in my actual life? What have I been knowing but not acting on?\n\nPart 2 \u2014 Ordinary Moment Practice (throughout the day): Set 5 reminders on your phone. Each time one goes off, wherever you are, pause. Take one conscious breath. Open your awareness beyond the surface of the moment. Ask: what is really happening here? What am I not seeing? What does this moment need from me?\n\nThis is the bridge between practice and life. It takes 10 seconds each time.",
    journalPrompt: "What specific change in how you live is your inner eye asking you to make right now? Be specific. Name it. What has been the cost of not acting on it? What would change if you did?",
  },
  {
    day: 33, title: 'The Activation Ceremony', week: 5, theme: 'Sacred Completion Ritual', duration: '60 minutes',
    teaching: "Today we mark the completion of the Activation and Expansion phase with a closing ceremony.\n\nCeremony is how human beings throughout all of history mark significant thresholds. Birth. Coming of age. Initiation into new capacities. The completion of your activation work is a genuine threshold. Something in you has changed. Not everything. Not finally. But genuinely. The inner eye is more open. The channel is clearer. The relationship between you and your deeper wisdom is more developed, trusted, and alive.\n\nThis deserves to be marked. Not with performance but with genuine acknowledgement and gratitude.\n\nSet aside 60 minutes. Find a space that feels sacred \u2014 your practice space set up more intentionally, somewhere in nature, or a room that carries significance. Cleanse the space. Open windows if possible. Light candles or incense if you use them.",
    practice: "THE CEREMONY:\n\nOPENING (5 min): Speak aloud or inwardly: \u201CI have completed three weeks of activation work. I have turned toward my inner world with honesty and courage. I have done uncomfortable things. I have faced what I was avoiding. I have opened where I was closed. I acknowledge this. I honour this.\u201D\n\nTHE REVIEW (10 min): Sit in stillness. Let the significant moments of the past three weeks arise: the first activation meditation, the energy clearing, the dream that stayed with you, the moment of genuine knowing, the resistance that gave way. Hold each with appreciation.\n\nTHE DECLARATION (10 min): Write or speak, completing this: \u201CThe inner eye that has been activated in me is...\u201D Write what it can see. What it is for. What responsibility it carries. What it asks of you. What you commit to doing with it. This is your sacred contract with your own awakening.\n\nTHE RECEPTION (15 min): Complete silence. You have spoken. Now receive. Open your awareness fully. Allow the inner eye to show you whatever it wishes at this moment of completion.\n\nTHE CLOSING (5 min): Hands on heart. Three deep breaths. \u201CI am grateful. I am changed. I am ready for what comes next.\u201D Sit quietly 5 minutes before moving.\n\nAFTER: Write everything in your journal. Share something in the community if moved to. Rest tonight.",
    journalPrompt: "What did you discover in the ceremony? What did the inner eye show you in the silence? What declaration did you make? What are you carrying forward?",
  },
  {
    day: 34, title: 'Activation Complete', week: 5, theme: 'Harvest & Preparation for Embodiment', duration: '30 minutes',
    teaching: "You have completed the Activation and Expansion phase.\n\nTwenty days. Twenty practices. Multiple layers of the inner eye opened, worked with, and beginning to integrate. Dreams more vivid and communicative. Energy more perceptible and navigable. Intuitive perception more reliable and trusted. Your specific gifts more clearly identified and intentionally developed.\n\nThe world needs people who can see clearly. Who can feel the truth beneath the surface. Who can act from genuine inner knowing rather than fear, conditioning, or others\u2019 expectations. Every person who genuinely develops their inner eye becomes a clearer channel for wisdom in their family, community, and world.\n\nIn Weeks 6-8 (Integration & Embodiment) you will: Ground every practice into a sustainable, personalised lifetime spiritual routine. Work with the specific areas of your life where guidance is most needed and challenging \u2014 relationships, vocation, creative expression, purpose. Develop your capacity to share your gifts naturally. Complete the cohort with a clear personal vision for the direction of your life.\n\nYou are in the home stretch. And home stretches are where the most important things happen.",
    practice: "Part 1 \u2014 The Harvest (20 min): Complete this in your journal:\n\nOf all the practices in the activation phase, which three had the deepest impact and why?\n\nWhat is the most significant thing your dream life has shown you?\n\nHow has your relationship with energy fields changed?\n\nWhat is your primary intuitive channel, and how has identifying it changed your relationship with inner guidance?\n\nWhat was the most challenging part of this phase? What did that challenge teach you?\n\nWho are you after these five weeks that you were not before you began?\n\nPart 2 \u2014 Letter to Future Self (10 min): Write a letter to yourself to be opened in one year. Describe who you are right now, at the end of the activation phase. What do you hope to tell yourself in twelve months about how you lived what you learned here?",
    journalPrompt: "Complete the harvest questions above. Then write one sentence that captures the essence of what these 20 days have meant to you. One sentence. Make it true.",
  },
]


function LoadingScreen() {
  return (
    <div style={{ minHeight:'100vh', display:'flex', alignItems:'center', justifyContent:'center', background:C.cream, fontFamily:sans }}>
      <div style={{ textAlign:'center' }}>
        <div style={{ fontSize:'3rem', marginBottom:'1rem' }}>🔥</div>
        <p style={{ color:C.muted }}>Loading your practice space...</p>
      </div>
    </div>
  )
}

function LockedScreen() {
  return (
    <div style={{ minHeight:'100vh', display:'flex', alignItems:'center', justifyContent:'center', background:C.cream, fontFamily:sans, padding:'2rem' }}>
      <div style={{ maxWidth:480, textAlign:'center', background:C.white, border:`1px solid ${C.border}`, borderRadius:16, padding:'3rem 2rem', boxShadow:'0 4px 24px rgba(0,0,0,0.06)' }}>
        <div style={{ fontSize:'3rem', marginBottom:'1rem' }}>🔒</div>
        <h2 style={{ fontFamily:serif, color:C.green, fontWeight:400, fontSize:'1.8rem', margin:'0 0 0.75rem' }}>Course Access Required</h2>
        <p style={{ color:C.muted, lineHeight:1.7, marginBottom:'2rem' }}>You need to enroll in a cohort to access the course content. Once payment is complete, David will activate your access within 24 hours.</p>
        <div style={{ display:'flex', flexDirection:'column', gap:'0.75rem' }}>
          <a href="/#pricing" style={{ display:'block', background:C.green, color:C.white, padding:'0.9rem', borderRadius:8, textDecoration:'none', fontWeight:500 }}>View Enrollment Options</a>
          <a href={`https://wa.me/27817904941?text=${encodeURIComponent('Hi David, I have completed payment and would like my course access activated.')}`} target="_blank" rel="noopener noreferrer" style={{ display:'block', background:'#25D366', color:C.white, padding:'0.9rem', borderRadius:8, textDecoration:'none', fontWeight:500 }}>💬 Message David on WhatsApp</a>
        </div>
      </div>
    </div>
  )
}

function CourseContent({ user }) {
  const { completed: completedDays, markDone, loading: progressLoading } = useProgress(user?.uid, 'week3-5')
  const [activeDay, setActiveDay] = useState(0)
  const days = completedDays || []

  const handleComplete = async (day) => { await markDone(day) }

  const currentDay = DAYS[activeDay]
  const progress = Math.round((days.length / 20) * 100)
  const wColor = weekColors[currentDay.week] || C.green

  if (progressLoading) return <LoadingScreen />

  return (
    <>
      <Head>
        <title>Weeks 3-5: Activation & Expansion — The Clarity Institute</title>
        <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,300;1,400&family=Jost:wght@300;400;500;600&display=swap" rel="stylesheet" />
      </Head>
      <div style={{ minHeight:'100vh', background:C.cream, fontFamily:sans }}>
        {/* Nav */}
        <nav style={{ background:C.white, borderBottom:`1px solid ${C.border}`, padding:'1rem 2rem', display:'flex', justifyContent:'space-between', alignItems:'center' }}>
          <Link href="/dashboard" style={{ fontFamily:serif, fontSize:'1.2rem', color:C.green, textDecoration:'none', fontWeight:600 }}>The Clarity Institute</Link>
          <div style={{ display:'flex', alignItems:'center', gap:'1rem' }}>
            <span style={{ fontSize:'0.82rem', color:C.muted }}>{progress}% complete</span>
            <Link href="/dashboard" style={{ fontSize:'0.85rem', color:C.muted, textDecoration:'none' }}>← Dashboard</Link>
          </div>
        </nav>

        <div style={{ maxWidth:1100, margin:'0 auto', padding:'2rem 1.5rem' }}>
          {/* Header */}
          <div style={{ marginBottom:'2rem' }}>
            <span style={{ fontSize:'0.75rem', fontWeight:600, letterSpacing:'0.15em', textTransform:'uppercase', color:C.orange, display:'block', marginBottom:'0.5rem' }}>Weeks 3–5</span>
            <h1 style={{ fontFamily:serif, fontSize:'2.2rem', color:C.green, fontWeight:300, margin:'0 0 0.5rem' }}>Activation & <em style={{ color:C.orange }}>Expansion</em></h1>
            <p style={{ color:C.muted, margin:0, fontSize:'0.95rem' }}>Open the Ajna chakra, develop your intuitive gifts, explore the subtle realms and discover your unique channel.</p>
            <div style={{ background:C.cream2, borderRadius:999, height:8, overflow:'hidden', marginTop:'1rem', maxWidth:400 }}>
              <div style={{ height:'100%', width:`${progress}%`, background:C.orange, borderRadius:999, transition:'width 0.5s ease' }} />
            </div>
          </div>

          <div style={{ display:'grid', gridTemplateColumns:'280px 1fr', gap:'2rem' }}>
            {/* Sidebar */}
            <div>
              <div style={{ background:C.white, border:`1px solid ${C.border}`, borderRadius:14, overflow:'hidden', position:'sticky', top:'1rem' }}>
                {DAYS.map((d, i) => {
                  const isActive = i === activeDay
                  const isComplete = days.includes(d.day)
                  const isWeekBreak = i === 0 || d.week !== DAYS[i-1]?.week
                  const wc = weekColors[d.week] || C.green
                  return (
                    <div key={d.day}>
                      {isWeekBreak && (
                        <div style={{ padding:'0.6rem 1rem', background:wc, fontSize:'0.72rem', fontWeight:600, color:C.white, textTransform:'uppercase', letterSpacing:'0.1em' }}>Week {d.week}</div>
                      )}
                      <button onClick={() => { setActiveDay(i); window.scrollTo(0,0) }} style={{
                        display:'flex', alignItems:'center', gap:'0.6rem', width:'100%', textAlign:'left', padding:'0.7rem 1rem',
                        background: isActive ? `${wc}10` : 'transparent', border:'none', borderBottom:`1px solid ${C.border}`,
                        borderLeft: isActive ? `3px solid ${wc}` : '3px solid transparent',
                        cursor:'pointer', fontFamily:sans, fontSize:'0.85rem', color: isActive ? wc : C.text, fontWeight: isActive ? 500 : 400,
                      }}>
                        <span style={{
                          width:22, height:22, borderRadius:'50%', display:'flex', alignItems:'center', justifyContent:'center',
                          fontSize:'0.7rem', fontWeight:600, flexShrink:0,
                          background: isComplete ? wc : C.cream, color: isComplete ? C.white : C.muted,
                          border: isComplete ? 'none' : `1px solid ${C.border}`,
                        }}>{isComplete ? '✓' : d.day}</span>
                        <span style={{ lineHeight:1.3 }}>{d.title}</span>
                      </button>
                    </div>
                  )
                })}
              </div>
            </div>

            {/* Main content */}
            <div>
              <div style={{ background:C.white, border:`1px solid ${C.border}`, borderRadius:16, padding:'2.5rem', marginBottom:'1.5rem' }}>
                <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:'1.5rem', flexWrap:'wrap', gap:'0.5rem' }}>
                  <div>
                    <span style={{ fontSize:'0.75rem', color:wColor, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.1em' }}>Day {currentDay.day} · {currentDay.theme}</span>
                    <h2 style={{ fontFamily:serif, fontSize:'2rem', color:C.green, fontWeight:300, margin:'0.25rem 0 0' }}>{currentDay.title}</h2>
                  </div>
                  <span style={{ fontSize:'0.8rem', color:C.muted, background:C.cream, padding:'0.3rem 0.75rem', borderRadius:999 }}>⏱ {currentDay.duration}</span>
                </div>

                {/* Teaching */}
                <div style={{ marginBottom:'2rem' }}>
                  <h3 style={{ fontSize:'0.8rem', fontWeight:600, color:C.brown, textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:'0.75rem' }}>Today's Teaching</h3>
                  {currentDay.teaching.split('\n\n').map((para, i) => (
                    <p key={i} style={{ color:C.text, fontSize:'0.95rem', lineHeight:1.85, margin:'0 0 1rem' }}>{para}</p>
                  ))}
                </div>

                {/* Practice */}
                <div style={{ background:`linear-gradient(135deg, #f0f4f0, ${C.cream})`, border:`1px solid ${C.green}25`, borderRadius:14, padding:'1.75rem', marginBottom:'2rem' }}>
                  <h3 style={{ fontSize:'0.8rem', fontWeight:600, color:C.green, textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:'0.75rem' }}>🧘 Today's Practice</h3>
                  {currentDay.practice.split('\n\n').map((para, i) => (
                    <p key={i} style={{ color:C.text, fontSize:'0.95rem', lineHeight:1.85, margin:'0 0 1rem' }}>{para}</p>
                  ))}
                </div>

                {/* Journal */}
                <div style={{ background:C.cream, borderLeft:`3px solid ${C.orange}`, borderRadius:'0 10px 10px 0', padding:'1.25rem 1.5rem', marginBottom:'2rem' }}>
                  <h3 style={{ fontSize:'0.8rem', fontWeight:600, color:C.orange, textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:'0.5rem' }}>📝 Journal Prompt</h3>
                  {currentDay.journalPrompt.split('\n\n').map((para, i) => (
                    <p key={i} style={{ color:C.text, fontSize:'0.95rem', lineHeight:1.75, margin:'0 0 0.5rem', fontStyle:'italic' }}>{para}</p>
                  ))}
                </div>

                {/* Buttons */}
                <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', flexWrap:'wrap', gap:'1rem' }}>
                  <button onClick={() => handleComplete(currentDay.day)} disabled={days.includes(currentDay.day)} style={{
                    background: days.includes(currentDay.day) ? C.cream : wColor,
                    color: days.includes(currentDay.day) ? wColor : C.white,
                    border: days.includes(currentDay.day) ? `1.5px solid ${wColor}` : 'none',
                    padding:'0.85rem 2rem', borderRadius:8, fontFamily:sans, fontSize:'0.95rem', fontWeight:500,
                    cursor: days.includes(currentDay.day) ? 'default' : 'pointer',
                  }}>{days.includes(currentDay.day) ? '✓ Day Completed' : 'Mark Day as Complete'}</button>

                  <div style={{ display:'flex', gap:'0.5rem' }}>
                    {activeDay > 0 && (
                      <button onClick={() => { setActiveDay(activeDay - 1); window.scrollTo(0,0) }} style={{
                        background:'transparent', color:C.muted, border:`1px solid ${C.border}`,
                        padding:'0.7rem 1.25rem', borderRadius:8, fontFamily:sans, fontSize:'0.85rem', cursor:'pointer',
                      }}>← Previous</button>
                    )}
                    {activeDay < DAYS.length - 1 && (
                      <button onClick={() => { setActiveDay(activeDay + 1); window.scrollTo(0,0) }} style={{
                        background:wColor, color:C.white, border:'none',
                        padding:'0.7rem 1.25rem', borderRadius:8, fontFamily:sans, fontSize:'0.85rem', cursor:'pointer',
                      }}>Next Day →</button>
                    )}
                    {activeDay === DAYS.length - 1 && (
                      <Link href="/week6-8" style={{
                        background:C.green, color:C.white, padding:'0.7rem 1.25rem',
                        borderRadius:8, textDecoration:'none', fontSize:'0.85rem', fontWeight:500,
                      }}>Continue to Weeks 6–8 →</Link>
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default function Week3_5() {
  const { user, loading, isPaid, isAdmin } = useAuth()
  const router = useRouter()
  useEffect(() => {
    if (!loading && !user) router.replace('/login?redirect=/week3-5')
  }, [loading, user, router])
  if (loading) return <LoadingScreen />
  if (!user) return <LoadingScreen />
  if (!isPaid && !isAdmin) return <LockedScreen />
  return <CourseContent user={user} />
}
