// pages/week6-8.js — Weeks 6–8: Integration & Embodiment — 18 days
import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Link from 'next/link'
import { useAuth } from '../lib/useAuth'
import { useProgress } from '../lib/useProgress'

const C = { green:'#3D5A3E', green2:'#2D4520', brown:'#6B4A2A', orange:'#C1581A', cream:'#FAF6F0', cream2:'#F2EBE0', text:'#2C1F14', muted:'#7A6A5A', border:'#E0D5C5', white:'#ffffff' }
const serif = "'Cormorant Garamond', serif"
const sans = "'Jost', sans-serif"
const weekColors = { 6: '#6B4A2A', 7: '#3D5A3E', 8: '#C1581A' }

const DAYS = [
  // ══════ WEEK 6: GROUNDING THE SACRED ══════
  {
    day: 35, title: 'The Return', week: 6, theme: 'Coming Home to the Body', duration: '30 minutes',
    teaching: "You have walked through fire. You have sat in the dark and seen light that is not light. You have heard the voice that speaks without sound. You have touched the edge of something vast and nameless and felt it touch you back.\n\nNow comes the most sacred task of all: bringing it home.\n\nIntegration is the forgotten art of the spiritual path. Many seekers spend their lives chasing peak experiences \u2014 the next vision, the next download, the next mystical encounter \u2014 without ever learning to weave those experiences into the fabric of their ordinary, breathing, walking, eating, sleeping life. They become spiritually rich and humanly impoverished. Their inner eye is open but their feet have left the ground.\n\nThe ancestors knew better. In the African initiation traditions, the period of integration after awakening was considered the most important phase of the entire journey. The sangoma who has received the calling must then learn to walk in the marketplace with the same presence they carried in the sacred cave. The mystic who has touched God must then learn to wash dishes with those same hands.\n\nWeeks 6 through 8 are about this sacred return. Not a retreat from what you have opened \u2014 never that. A deepening of it. A rooting of it so deep into the soil of your daily life that it becomes inseparable from who you are. Not something you do. Something you are.\n\nThe inner eye that has been activated in you is not a toy. It is not a party trick. It is a faculty of perception that carries responsibility \u2014 the responsibility to live in alignment with what you can now see. To speak truth when silence would be easier. To act from knowing when doubt would be more comfortable. To love when the world offers every reason not to.\n\nThis is the real work. Everything before this was preparation.",
    practice: "Today we begin with a practice of radical re-embodiment.\n\nStand barefoot on the earth if possible \u2014 grass, soil, stone. If you are indoors, stand barefoot on the floor.\n\nClose your eyes. Feel the soles of your feet. Feel the weight of your body pressing downward. Feel gravity \u2014 that great love of the earth that holds you without asking anything in return.\n\nBegin to breathe very slowly. With each inhale, draw the energy of the earth upward through the soles of your feet, through your legs, through your belly, through your heart, through your throat, through your third eye, through your crown. With each exhale, allow all that you have gathered in these weeks \u2014 every insight, every vision, every tear, every moment of clarity \u2014 to flow downward through the same path and root itself in the earth beneath you.\n\nYou are planting the tree of your awakening. The roots must go as deep as the branches reach high.\n\nDo this for 15 minutes. Then sit and perform your full daily practice: grounding, protection, breathwork, Ajna activation, and 5 minutes of silent receptive awareness.\n\nClose by placing both palms flat on the earth and saying: I am here. I am home. What I have received, I will live.",
    journalPrompt: "What does it mean to you to \u2018bring it home\u2019? What aspect of your awakened perception feels most natural in daily life? What aspect still feels separate from ordinary reality \u2014 like something you access only in practice? How might you bridge that gap?",
  },
  {
    day: 36, title: 'The Mirror of Relationship', week: 6, theme: 'Seeing Others with the Inner Eye', duration: '35 minutes',
    teaching: "Now that the inner eye is open, you will see people differently. This is not optional. It is a consequence of perception. Once you can see, you cannot unsee.\n\nYou will notice things about the people in your life that you did not notice before. The pain beneath someone\u2019s anger. The fear beneath someone\u2019s control. The loneliness beneath someone\u2019s performance. The light in someone who does not yet know they carry it.\n\nThis is both a gift and a weight. A gift because genuine seeing is the foundation of genuine love. A weight because you can no longer pretend you do not know what you know.\n\nIn the Sufi tradition, there is a teaching that every person you encounter is a mirror of an aspect of yourself. The qualities that attract you in others are qualities awakening in you. The qualities that repel you are shadows you have not yet integrated. The people who trigger you most deeply are your greatest teachers \u2014 not because they are wise, but because they illuminate what is unresolved in your own psyche.\n\nThe Zulu concept of ubuntu \u2014 \u201CI am because we are\u201D \u2014 points to the same truth. Your awakening is not a private event. It occurs within the web of relationship. Every relationship you are in is both a mirror and a crucible \u2014 reflecting who you are and forging who you are becoming.\n\nThe inner eye does not separate you from people. It connects you more deeply. But the nature of the connection changes. It becomes more honest. More vulnerable. More demanding of truth. And infinitely more tender.\n\nToday we work with the spiritual dimension of your closest relationships.",
    practice: "Part 1 \u2014 The Five Mirrors (15 min):\n\nIn your journal, write the names of the five people you interact with most frequently. For each person, answer:\n\nWhat quality in them do I most admire? (This is a quality awakening in you.)\nWhat quality in them most frustrates me? (This is a shadow you have not yet owned.)\nWhat do I feel in my body when I am with them? (This is your energy body\u2019s honest report.)\nWhat truth have I been withholding from this relationship? (This is the inner eye\u2019s guidance.)\n\nPart 2 \u2014 The Compassion Meditation (15 min):\n\nSit in meditation. Bring each of these five people into your awareness, one at a time. For each person, visualise them sitting across from you. Look into their eyes with your inner sight. See beyond their personality, their habits, their role in your life. See the being beneath the surface \u2014 the one who is also seeking, also struggling, also carrying a light they may not know how to express.\n\nSilently say to each: I see you. I honour your journey. I release the version of you that I created in my mind. I meet you as you are.\n\nFeel what shifts in your body as you do this. Notice which person was easiest to see clearly, and which was hardest.",
    journalPrompt: "Which relationship is your greatest mirror right now? What is it showing you about yourself that you have been reluctant to see? What would change in that relationship if you spoke the truth your inner eye has been revealing?",
  },
  {
    day: 37, title: 'The Sacred Wound', week: 6, theme: 'Transforming Pain into Purpose', duration: '40 minutes',
    teaching: "There is a teaching that appears in almost every mystical tradition, though it is expressed differently in each: your deepest wound carries the seed of your greatest gift.\n\nThe Greek myth of Chiron, the wounded healer, tells of a being who could heal everyone except himself \u2014 and it was precisely this wound that made him the greatest healer of all. In the sangoma tradition of Southern Africa, the healer\u2019s calling almost always begins with illness, crisis, or profound suffering \u2014 the thwasa sickness is understood not as pathology but as the breaking open of the vessel so that spirit can enter. In the Christian mystical tradition, the wounds of Christ become the doorway through which divine light enters the world.\n\nYour wound is not a mistake. It is not evidence that something went wrong. It is the precise point at which your awakening entered your life.\n\nConsider: the thing that hurt you most is almost certainly related to the thing you are most passionate about healing in the world. The person who was abandoned becomes the one who creates belonging. The one who was silenced becomes the voice for the voiceless. The one who was told they were too much or not enough becomes the one who teaches others their inherent worth.\n\nThis is not a sentimental reframing. It is an alchemical truth. The fire that burns you is the same fire that forges you. But the transformation from wound to gift is not automatic. It requires conscious work. It requires you to turn toward the wound with the same courage with which you opened your inner eye \u2014 and to ask it: what did you come to teach me? What am I meant to do with what I have survived?\n\nToday we do that work.",
    practice: "This is deep work. Create a sacred container for it. Light a candle. Sit in your practice space. Ground yourself fully \u2014 roots deep, protection in place.\n\nPart 1 \u2014 Naming the Wound (10 min):\n\nIn your journal, write the story of your deepest wound. Not every detail \u2014 the essence. The experience that shaped you most. The thing that broke something open in you. Write it as a witness, not a victim. Write it as someone who has survived and is now ready to understand why.\n\nPart 2 \u2014 The Alchemical Questions (10 min):\n\nWhat did this wound teach me that I could not have learned any other way?\n\nWhat capacity did it forge in me? (Empathy? Strength? Sensitivity? Discernment? Compassion?)\n\nHow has this wound shaped what I care most about in the world?\n\nIf this wound carries a gift, what is that gift? And who is it for?\n\nPart 3 \u2014 The Wound Meditation (15 min):\n\nClose your eyes. Bring the wound into your awareness \u2014 not to relive it, but to hold it with the eyes of the mystic rather than the eyes of the sufferer. Visualise it as a physical location in your body. Breathe into that location. With each breath, see it transform \u2014 from darkness to light, from contraction to expansion, from wound to womb. See it becoming the birthplace of something new. Something that wants to come through you into the world.\n\nSit with whatever arises. You may weep. You may feel relief. You may feel nothing yet and find it comes later. All responses are sacred.\n\nClose by placing your hands on the area of your body where the wound lives and saying: I honour you. I understand now. Show me what to build from what was broken.",
    journalPrompt: "What did you discover about the relationship between your wound and your purpose? What gift has your pain been trying to give you? How might you offer that gift to others?",
  },
  {
    day: 38, title: 'Vocation and the Inner Call', week: 6, theme: 'Aligning Work with Soul Purpose', duration: '35 minutes',
    teaching: "The word vocation comes from the Latin vocare \u2014 to call. A vocation is not merely a job. It is a calling. It is the specific way your soul has chosen to express itself through the medium of work, service, and creative contribution.\n\nThe inner eye, when fully active, does not merely see visions in meditation. It sees the deeper pattern of your life. It sees what you are here to do \u2014 not in a grand, dramatic sense (though it may be that), but in the specific, grounded, practical sense of how you are meant to spend your days.\n\nMany people live their entire lives without ever asking: what am I actually called to do? They follow the path laid out by family, culture, economics, or fear. They build lives that look successful from the outside but feel hollow from the inside. The inner eye\u2019s great gift in the realm of vocation is clarity \u2014 the ability to distinguish between what you are expected to do and what you are called to do.\n\nIn the African understanding, every person is born with a specific destiny \u2014 a blueprint that the soul agreed to before entering this life. The Yoruba call it ori \u2014 your personal destiny and the inner head that carries it. The sangoma tradition holds that those called to heal cannot rest until they answer the call \u2014 resistance to one\u2019s vocation creates spiritual and even physical illness.\n\nYou may not be called to be a healer in the traditional sense. But you are called to something. The inner eye knows what it is. Today we listen.",
    practice: "Part 1 \u2014 The Vocation Inventory (10 min):\n\nIn your journal, answer quickly and honestly:\n\nWhat activities make me lose track of time?\nWhat problems in the world make me angry or heartbroken?\nWhat would I do if money were not a factor?\nWhat did I love doing as a child before the world told me to be practical?\nWhat do people consistently ask me for help with?\nWhat knowledge or skill do I have that feels effortless to me but valuable to others?\n\nPart 2 \u2014 The Inner Eye Enquiry (15 min):\n\nSit in meditation. Ground, protect, activate the Ajna. Then ask your inner eye directly: What am I here to do? What is my work in this lifetime?\n\nDo not demand a specific job title. Ask for the essence. The quality. The direction. You may receive an image, a feeling, a word, or a knowing. Whatever form the answer takes, receive it without argument.\n\nThen ask: What is the next step? Not the whole path \u2014 just the next step. The inner eye almost always answers this question with startling clarity when we are willing to hear.\n\nPart 3 \u2014 The Commitment (5 min):\n\nWrite in your journal: The work I am called to is... The next step I will take is... I commit to taking this step within [timeframe].\n\nSign it. Date it. This is a contract between your awakened self and your daily life.",
    journalPrompt: "What did the inner eye show you about your vocation? Did the answer surprise you, or confirm something you have always sensed? What is the next step, and what has been stopping you from taking it?",
  },
  {
    day: 39, title: 'Creative Fire', week: 6, theme: 'Channelling Vision into Expression', duration: '35 minutes',
    teaching: "The inner eye does not only receive. It creates.\n\nEvery great work of art, every breakthrough invention, every inspired piece of writing, every melody that moves the soul \u2014 these did not originate in the thinking mind. They came from somewhere deeper. They were received before they were constructed. The artist, the poet, the composer, the inventor \u2014 each is a channel through which something invisible becomes visible.\n\nThe creative impulse and the spiritual impulse are not separate forces. They are the same force expressing through different channels. When the Ajna chakra is active, creativity is not something you struggle to produce. It is something that flows through you when you create the conditions for it.\n\nIn many African traditions, the creative act is understood as a form of prayer. The sculptor who carves a mask is not merely making an object \u2014 they are calling a spirit into form. The drummer who plays is not merely keeping rhythm \u2014 they are opening a doorway between worlds. The poet who speaks is not merely arranging words \u2014 they are giving voice to what the ancestors wish to say.\n\nYou carry creative fire. It may express as writing, music, visual art, teaching, cooking, gardening, building, speaking, leading, healing, or a hundred other forms. The specific form matters less than the quality of presence you bring to it. When you create from the inner eye rather than from the thinking mind alone, what emerges carries a charge \u2014 a quality of aliveness that others can feel.\n\nToday we open the creative channel and let something come through.",
    practice: "Part 1 \u2014 Activating the Creative Channel (10 min):\n\nSit in meditation. Ground and activate the Ajna. Then bring your awareness to the sacral chakra \u2014 just below the navel, the seat of creative and generative energy. Visualise warm orange light pulsing there. Now visualise a golden thread connecting the sacral centre to the third eye \u2014 linking creative energy with spiritual vision. Breathe into both centres simultaneously. Feel them communicating. Feel creative energy rising to meet spiritual sight.\n\nPart 2 \u2014 Unfiltered Creation (20 min):\n\nChoose a creative medium \u2014 whatever calls to you. Writing. Drawing. Singing. Movement. Cooking. Building. Speaking aloud. Whatever form your creativity naturally takes.\n\nSet a timer for 20 minutes. Create without stopping, without editing, without judging. If you are writing, let the pen move without your mind directing it. If you are drawing, let the hand move. If you are singing, let the voice go where it wants. If you are moving, let the body lead.\n\nThe instruction is simple: get out of the way and let something come through.\n\nDo not worry about quality. This is not about producing something good. It is about opening the channel between the inner world and the outer world. What comes through may surprise you. It may feel raw, strange, beautiful, disturbing, or sacred. Let it be whatever it is.\n\nPart 3 \u2014 Witnessing (5 min):\n\nWhen the timer ends, sit quietly and look at what you created. Read what you wrote. Look at what you drew. Remember what you sang or how you moved. Witness it without judgment. Ask: where did this come from? What is it trying to say?",
    journalPrompt: "What emerged during the unfiltered creation? What surprised you? What felt like it came from somewhere deeper than your ordinary mind? How does it feel to create from the inner eye rather than from the thinking mind?",
  },
  {
    day: 40, title: 'The Ancestor Within', week: 6, theme: 'Connecting to Lineage & Wisdom', duration: '40 minutes',
    teaching: "You are not the first person to walk this path. You are not alone on it now. And you will not be the last.\n\nBehind you stands a line of beings stretching back through time immemorial \u2014 your ancestors. Not merely your biological ancestors, though they are included. But also your spiritual ancestors: every seeker, every mystic, every healer, every dreamer who walked toward the light before you and whose footprints you now follow.\n\nIn the African spiritual worldview, the ancestors are not merely memories. They are living presences. They exist in the spiritual dimension that interpenetrates the physical world, and they take an active interest in the lives of their descendants. They carry wisdom accumulated across lifetimes. They can be communicated with. They can offer guidance, protection, and blessing.\n\nThe Western world has largely lost this understanding, reducing ancestors to names on a family tree. But the inner eye, when open, can perceive what the ancestors themselves never stopped offering: their presence, their love, and their counsel.\n\nYou do not need to follow a specific tradition to connect with ancestral wisdom. You need only be willing to acknowledge that you did not arrive here alone, that intelligence and love precede your individual existence, and that the line of light that led to you continues to shine.\n\nToday we open the ancestral channel.",
    practice: "Part 1 \u2014 Creating an Ancestral Space (5 min):\n\nIf you have photographs of deceased grandparents, great-grandparents, or other ancestors, place them somewhere visible. If you have none, simply set a glass of water and a white candle on a clean surface \u2014 the water represents the flow of life through generations, the candle represents the light that endures.\n\nPart 2 \u2014 The Ancestral Meditation (25 min):\n\nSit before your ancestral space. Ground yourself deeply. Close your eyes.\n\nVisualize yourself standing at the edge of a great river. On the far bank, in mist or golden light, stand the figures of those who came before you. You may see specific faces. You may see only silhouettes. You may feel their presence without seeing anything. All are valid.\n\nSpeak to them, aloud or in your heart: I acknowledge you. I honour the life you lived so that I might live. I carry your blood, your struggles, your unfinished dreams, and your unspoken prayers. I ask for your guidance as I walk this path.\n\nThen be silent. Listen with your inner ear. Feel with your inner body. See with your inner eye. They may communicate through images, feelings, words, memories, or a quality of presence that carries its own message.\n\nStay here for 20 minutes. Do not rush.\n\nPart 3 \u2014 The Offering (5 min):\n\nPour fresh water into the glass (or refresh it). Light the candle if it is not already lit. Say: Thank you. I will live in a way that honours what you gave. I carry the light forward.\n\nThis can become a regular practice \u2014 tending the ancestral space weekly with fresh water, a candle, and a moment of gratitude.",
    journalPrompt: "What did you experience in the ancestral meditation? Did any specific ancestor make their presence known? What quality of wisdom or guidance did you receive? How does it feel to acknowledge yourself as part of a lineage?",
  },
  {
    day: 41, title: 'Week 6 Integration', week: 6, theme: 'The Sacred Pause', duration: '20 minutes',
    teaching: "You have spent a week grounding the sacred into the human.\n\nYou returned to the body. You looked into the mirror of your relationships with awakened eyes. You turned toward your deepest wound and found the gift inside it. You listened for your vocation. You opened the creative channel. You connected with the wisdom of those who came before you.\n\nThis is the most human week of the cohort. And perhaps the most important. Because an awakened eye that does not change how you live, love, create, and serve is merely a decoration. It becomes real only when it touches the ordinary \u2014 when the sacred seeps into the mundane and transforms it from the inside.\n\nPause today. Let the week\u2019s work settle. The roots are going deeper than you can feel. Trust the process beneath the surface.",
    practice: "Part 1 \u2014 Review (10 min): Read your journal entries from Days 35-40. Notice the thread connecting them. What story is emerging about who you are becoming?\n\nPart 2 \u2014 The Integration Questions:\n\nWhich of this week\u2019s practices touched me most deeply, and why?\n\nWhat truth about my relationships has the inner eye revealed that I cannot ignore?\n\nWhat is my wound\u2019s gift, and am I ready to offer it?\n\nWhat did the ancestors say?\n\nWhat is the one change I am being asked to make in my actual, daily, ordinary life?\n\nPart 3 \u2014 Sacred Rest: Do something that nourishes your body and soul. Walk slowly. Cook with attention. Sit in sunlight. Let the earth hold you.",
    journalPrompt: "If your inner eye could write you one letter about how to live from this point forward, what would it say? Write that letter now \u2014 from your deepest self to your daily self.",
  },
  // ══════ WEEK 7: WALKING BETWEEN WORLDS ══════
  {
    day: 42, title: 'The Mystic in the Marketplace', week: 7, theme: 'Spiritual Presence in Daily Life', duration: '30 minutes',
    teaching: "There is an ancient Zen saying: Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water.\n\nThe tasks do not change. You change. And because you have changed, the same tasks become doorways to presence rather than obstacles to escape.\n\nThe mystic in the marketplace is not the one who floats above the crowd in a cloud of incense. It is the one who is more present than anyone else in the room. More attentive. More responsive. More alive to what is actually happening beneath the surface of things.\n\nYou have spent five weeks developing extraordinary inner capacities. This week we practise using them in the most ordinary circumstances imaginable: at work, in traffic, during a difficult conversation, while preparing a meal, while scrolling your phone, while lying awake at 3am wondering about your life.\n\nThe Sufi tradition speaks of keeping one eye on the marketplace and one eye on the Beloved \u2014 maintaining dual awareness, participating fully in the world while remaining connected to the deeper dimension. This is not splitting your attention. It is expanding it. The inner eye, when integrated, does not require you to withdraw from life. It allows you to be more fully in life than ever before.\n\nThis is the difference between a spiritual practitioner and a spiritually awakened human being. The practitioner does the practices. The awakened one lives as the practice.",
    practice: "Today\u2019s practice takes place entirely outside your meditation space.\n\nThe Presence Practice \u2014 do all five throughout your day:\n\n1. MORNING CONSECRATION (2 min): Before you leave your home, stand at the door. Take three breaths. Say inwardly: \u201CToday I walk with open eyes \u2014 both the outer and the inner. Everything I encounter is my teacher. Everyone I meet is a mirror of the divine.\u201D Step through the door as if crossing a threshold into sacred territory. Because you are.\n\n2. THE CONSCIOUS MEAL (15 min): Choose one meal today and eat it in complete silence, without screens, without reading, without distraction. Before you begin, look at the food. Consider the chain of life that brought it to you \u2014 the sun, the rain, the soil, the hands that planted and harvested and transported and prepared. Take your first bite as if you have never tasted food before. Eat slowly. Taste everything. This is the inner eye applied to the tongue.\n\n3. THE INVISIBLE PRACTICE (throughout the day): Three times today, do something kind for someone without them knowing. Hold a door. Leave a generous tip. Send a silent blessing to a stranger who looks tired. Clean something that isn\u2019t yours to clean. The inner eye sees what is needed. The awakened heart responds without seeking credit.\n\n4. THE DIFFICULT MOMENT (when it arises): At some point today, something will frustrate, annoy, or challenge you. When it does, before you react, take one conscious breath. Feel your feet on the ground. Open your inner eye. Ask: what is actually happening here, beneath the surface? What is this moment asking of me? Then respond from that deeper place.\n\n5. EVENING REVIEW (5 min): Before sleep, review your day through the lens of the inner eye. Where were you most present? Where did you lose presence? What did you see today that you would have missed six weeks ago?",
    journalPrompt: "How did it feel to carry the inner eye into ordinary moments? Which of the five practices felt most natural? Which was most challenging? What did you see in the \u2018difficult moment\u2019 that you would not have seen before this cohort?",
  },
  {
    day: 43, title: 'The Language of Silence', week: 7, theme: 'Deep Listening & Sacred Communication', duration: '35 minutes',
    teaching: "Most communication in the human world happens through words. But the deepest communication \u2014 the kind that actually changes things \u2014 happens through silence.\n\nWhen you truly listen to another person \u2014 not waiting for your turn to speak, not formulating your response, not filtering what they say through your own agenda \u2014 something extraordinary occurs. A space opens between you. In that space, truth can emerge that neither of you expected. This is the inner eye applied to the art of listening.\n\nThe ancient traditions understood that silence is not the absence of communication. It is the deepest form of it. In the Quaker tradition, worship happens in shared silence, and when someone speaks, it is understood as spirit moving through them. In the African tradition of the indaba (council), deep listening \u2014 listening with the whole body, the whole heart \u2014 is considered a sacred act. The Tibetan master Milarepa said: \u201CIt is better to sit in silence than to speak without knowing.\u201D\n\nYour inner eye has been trained to perceive. Now we train it to listen. Not only to the words people speak, but to what they mean beneath the words. To the emotion behind the sentence. To the need behind the demand. To the fear behind the anger. To the love behind the distance.\n\nThis is the gift you now carry: the ability to hear what is actually being said. It will transform every relationship you have.",
    practice: "Part 1 \u2014 The Listening Fast (morning):\n\nFor the first two hours of your day, speak only when absolutely necessary. Listen to everything \u2014 the sounds of your home, the birds, the traffic, the quality of silence itself. Notice how much richer the world becomes when you are not filling it with your own voice.\n\nPart 2 \u2014 Sacred Listening Practice (20 min):\n\nIf you have a willing partner (friend, family member, partner), do this exercise: Sit facing each other. One person speaks for 5 minutes about whatever is most alive in them right now. The other listens in complete silence \u2014 no nodding, no affirming sounds, no reactions. Simply receiving with full presence and an open inner eye.\n\nAfter 5 minutes, the listener reflects back not what was said, but what was felt beneath the words. \u201CWhat I heard beneath your words was...\u201D or \u201CWhat I felt as you spoke was...\u201D\n\nThen switch roles.\n\nIf you do not have a partner available, do this with yourself: sit in silence and ask your inner self to speak. Listen with the same quality of sacred attention. Write what you hear.\n\nPart 3 \u2014 The Evening Enquiry (5 min):\n\nBefore sleep, ask: What did I hear today that I normally would have missed? What was someone trying to tell me that their words could not carry?",
    journalPrompt: "What did you discover during the listening fast? What did you hear beneath someone\u2019s words today? How does deep listening change the quality of connection?",
  },
  {
    day: 44, title: 'Walking the Dreamtime', week: 7, theme: 'Living Between Waking & Dreaming', duration: '35 minutes',
    teaching: "The Aboriginal Australians speak of the Dreamtime \u2014 not as a past event but as an ongoing, ever-present dimension of reality that underlies and gives meaning to the physical world. The Dreamtime is not somewhere else. It is here, now, woven through the fabric of ordinary experience for those who have eyes to see.\n\nYou have been developing those eyes. Your dream life has become richer and more communicative. Your waking perception has expanded. Now we explore the territory between \u2014 the liminal space where dreaming and waking overlap.\n\nThis is the state of consciousness that mystics across traditions have described as the most fertile ground for revelation. The hypnagogic state (between waking and sleeping) and the hypnopompic state (between sleeping and waking) are not merely transitional. They are states of consciousness in their own right, with unique properties that neither full waking nor full sleeping possess.\n\nIn these liminal states, the rational mind is soft enough to allow the inner eye full expression, while consciousness remains alert enough to receive and remember what is shown. It is here that the most profound visions, the clearest guidance, and the deepest encounters with the numinous tend to occur.\n\nThe ancient Egyptian mystery schools trained initiates to remain conscious during the transitions between waking and sleeping \u2014 recognising these thresholds as the moments when the veil between worlds is thinnest. The Tibetan Buddhist practice of dream yoga is essentially this: maintaining awareness as you cross the threshold into sleep, and again as you cross back into waking.",
    practice: "Part 1 \u2014 The Threshold Practice (tonight):\n\nTonight, as you lie in bed and feel yourself beginning to drift toward sleep, hold your awareness at the threshold. Do not try to stay fully awake. Do not let yourself fall fully asleep. Rest in the between.\n\nYou may notice images beginning to form \u2014 faces, landscapes, symbols, colours. These hypnagogic images are the inner eye\u2019s first language when the thinking mind relaxes its grip. Simply observe them without engaging. Watch them like clouds passing. If one image feels significant or charged, hold your attention on it gently and see what unfolds.\n\nIf you fall asleep, that is fine. The intention itself trains the capacity over time.\n\nPart 2 \u2014 The Morning Threshold (tomorrow):\n\nWhen you wake, before opening your eyes, rest in the hypnopompic state for 2-3 minutes. Notice what images, feelings, or knowings are present in this between-space. Ask: is there a message for me in this threshold? Write everything in your journal before the waking mind takes over.\n\nPart 3 \u2014 Waking Dreamtime (during the day, 10 min):\n\nAt some point today, sit quietly and allow your eyes to go soft \u2014 the same soft gaze you used for aura reading. Look at your ordinary surroundings as if you are seeing them in a dream. What symbolic meaning might this room carry? What is this moment trying to tell you if you read it like a dream? This practice begins to dissolve the hard boundary between dreaming and waking perception.",
    journalPrompt: "What did you experience in the threshold states? What images appeared in the hypnagogic space? What was present in the hypnopompic space upon waking? How does it feel to read your waking life as if it were a dream?",
  },
  {
    day: 45, title: 'The Ethics of Seeing', week: 7, theme: 'Power, Responsibility & Humility', duration: '30 minutes',
    teaching: "With perception comes power. And with power comes the absolute necessity of ethics.\n\nYou can now sense things about people that they have not told you. You can feel the energy of a room before anyone speaks. You may receive information about situations before they unfold. You can see patterns that others miss. This is real power. And like all real power, it can be used to serve or to manipulate, to heal or to control, to illuminate or to impress.\n\nEvery tradition that develops the inner eye also develops a strict ethical code around its use. The sangoma tradition has elaborate protocols around consent, confidentiality, and the responsible use of spiritual sight. The yogic tradition teaches the yamas and niyamas \u2014 ethical restraints and observances \u2014 as prerequisites, not afterthoughts, to the development of siddhis (spiritual powers). The Christian contemplative tradition warns repeatedly against spiritual pride \u2014 the subtle corruption that occurs when one begins to feel special because of what they can perceive.\n\nHere are the principles that will keep your gift clean:\n\nCONSENT: Never read someone without their knowledge and permission. Your perception of their energy field, emotions, or situation is not an invitation to probe. You would not read someone\u2019s diary without asking. Do not read their energy without asking.\n\nHUMILITY: Your perceptions are filtered through your own psychology \u2014 your projections, your wounds, your desires, your fears. No human perception is perfectly objective. Hold everything you receive lightly and with the honest caveat that you may be wrong.\n\nSERVICE: The inner eye exists to serve, not to perform. If you find yourself wanting to demonstrate your abilities, impress someone, or gain advantage through your perception, you have drifted from the path. Return to service.\n\nSILENCE: Not everything you see needs to be spoken. The wise seer knows when to speak and when to hold. Sometimes the most powerful use of perception is silent compassion \u2014 seeing someone\u2019s pain without announcing that you see it, and simply being more tender with them because you do.\n\nACCOUNTABILITY: Have at least one person in your life \u2014 a mentor, a fellow practitioner, a trusted friend \u2014 to whom you can speak honestly about your inner experiences. Spiritual development without accountability is a recipe for self-deception.",
    practice: "Part 1 \u2014 The Ethical Inventory (15 min):\n\nIn your journal, answer honestly:\n\nHave I ever used my sensitivity to manipulate, even subtly? (Being aware of someone\u2019s insecurity and using it to influence them, for example.)\n\nHave I shared intuitive impressions with someone who did not ask for them?\n\nHave I felt superior to others because of what I can perceive?\n\nHave I used my spiritual practice as a way to avoid rather than engage with the difficult parts of being human?\n\nDo I have someone in my life who can hold me accountable for how I use these gifts?\n\nAnswer without shame. These are human tendencies, not moral failures. Naming them is how you prevent them from operating unconsciously.\n\nPart 2 \u2014 The Humility Meditation (10 min):\n\nSit in meditation. Bring your awareness to the Ajna. Then intentionally soften it. Not close it \u2014 soften it. Feel the difference between perceiving with grasping (I want to see, I want to know) and perceiving with surrender (I am available to what wishes to be shown).\n\nThe second posture is the ethical posture. It is perception in service of truth rather than in service of ego.\n\nHold this soft, receptive quality for 10 minutes. Notice how different it feels from the active seeking you may have practised in earlier weeks. Both have their place. But the posture of humble receptivity is the one that sustains a lifetime of clean seeing.",
    journalPrompt: "Where have you been most tempted to misuse your developing perception? What does humility actually look like in the context of spiritual sight? Who in your life can hold you accountable?",
  },
  {
    day: 46, title: 'The Body as Temple', week: 7, theme: 'Sacred Embodiment Practices', duration: '40 minutes',
    teaching: "The body is not an obstacle to spiritual perception. It is the instrument through which spiritual perception expresses itself in the world.\n\nThere is a strand of spiritual teaching \u2014 found in both Eastern and Western traditions \u2014 that treats the body as something to transcend, escape, or deny. This is a profound misunderstanding. The body is not the prison of the soul. It is the temple. And temples are not abandoned. They are consecrated, cared for, and honoured.\n\nIn the African understanding, the body is understood as a vessel for spiritual force. The Yoruba concept of ase \u2014 the power of life itself, the divine energy that animates all things \u2014 moves through the body. When the body is cared for, the channels are clear and ase flows freely. When the body is neglected, abused, or treated with contempt, the channels constrict and spiritual perception dulls.\n\nYour body has carried you through this entire cohort. It has sat in meditation for hours. It has shaken and wept during energy clearing. It has held still while the inner eye opened. It has processed every insight, every vision, and every integration. It deserves your reverence.\n\nToday we honour the body as what it is: sacred ground.",
    practice: "Part 1 \u2014 The Body Gratitude Ritual (15 min):\n\nStand before a mirror if possible, or simply stand with eyes closed. Beginning at the crown of your head and moving slowly downward, bring your awareness to each part of your body and offer it specific gratitude:\n\nMy head \u2014 thank you for holding the inner eye. My eyes \u2014 thank you for both the outer and inner seeing. My ears \u2014 thank you for hearing what is spoken and unspoken. My throat \u2014 thank you for carrying my truth into the world. My heart \u2014 thank you for feeling everything, even when it hurt. My hands \u2014 thank you for creating and for healing. My belly \u2014 thank you for the fire of will and the home of intuition. My legs \u2014 thank you for carrying me through this journey. My feet \u2014 thank you for connecting me to the earth.\n\nFeel each part as you speak to it. This is not performance. It is communion with your own body.\n\nPart 2 \u2014 Sacred Movement (15 min):\n\nPut on music that moves you \u2014 drumming, ambient sound, or whatever stirs your body. Close your eyes. Begin to move without any plan or choreography. Let the body lead. The thinking mind is a guest here, not the host.\n\nMove for 15 minutes. Let the movement be prayer. Let it be gratitude. Let it be whatever the body needs to express. If tears come, let them. If laughter comes, let it. If stillness comes in the middle of movement, honour it.\n\nPart 3 \u2014 Nourishment (10 min):\n\nPrepare something simple and beautiful to eat or drink. A cup of tea. A piece of fruit. Warm water with lemon and honey. Prepare it with the attention you would give a sacred offering \u2014 because it is one. Consume it slowly, with full presence. Your body is the temple. This is the offering.",
    journalPrompt: "How do you truly treat your body? With reverence or with neglect? What changed when you spoke gratitude to each part of your body? What did the sacred movement reveal?",
  },
  {
    day: 47, title: 'The Night Vigil', week: 7, theme: 'Extended Practice in Darkness', duration: '60 minutes (evening)',
    teaching: "In the initiation traditions of Africa, Egypt, Greece, and the ancient world, the night vigil was a pivotal event. The initiate would sit alone in darkness \u2014 sometimes in a cave, sometimes in a temple, sometimes in the wilderness \u2014 for an entire night, maintaining awareness while the world slept.\n\nThe night vigil is a microcosm of the entire spiritual journey: you sit with what is. You face what arises. You do not run. You stay.\n\nThere is something that happens in extended darkness and silence that cannot happen in a 15-minute morning meditation. The mind exhausts its repertoire of distractions. The body settles past its usual restlessness. The layers of consciousness that normally operate beneath the threshold of awareness begin to surface. The inner eye, freed from the tyranny of constant stimulation, perceives with a clarity that is rarely available in the noise of daytime life.\n\nYou will not sit all night (unless you wish to). But tonight, we do an extended evening practice of one hour in darkness. This is the deepest sitting of the entire cohort.",
    practice: "THE NIGHT VIGIL (60 minutes):\n\nChoose a time after dark \u2014 the later the better. 9pm, 10pm, midnight if you are willing. Create complete darkness in your practice space. No candle tonight. No light at all. Turn off all devices. Silence everything.\n\nSit comfortably. You will be here for one hour. Arrange yourself so that you can be genuinely comfortable for that duration. A chair is fine. Cushion is fine. Whatever supports you.\n\nBegin with 10 minutes of grounding and protection. Root deeply. Seal your field.\n\nThen simply sit. Eyes open in the darkness. No technique. No visualisation. No breathwork beyond your natural breath. Simply be present with what is.\n\nThe first 15-20 minutes may be restless. The mind will protest. Stay.\n\nThe next 15-20 minutes, something begins to settle. The mind runs out of things to say. A deeper quiet emerges. Stay.\n\nThe final 20 minutes are the vigil\u2019s gift. In this deep, extended stillness, the inner eye may show you things it has been waiting to show you. Or it may offer you nothing but silence. Both are the teaching. The willingness to sit with whatever arises \u2014 or with nothing \u2014 without fleeing, without distracting, without needing it to be anything other than what it is \u2014 this is the heart of all spiritual practice.\n\nWhen the hour is complete, do not turn on lights immediately. Sit for 5 more minutes in the dark. Then very slowly, gently, bring a small light into the room. Write in your journal by this dim light. Then sleep.",
    journalPrompt: "What happened in the darkness? What arose in the first restless phase? What emerged in the deep stillness? What did the silence say? What did you learn about yourself by simply staying?",
  },
  {
    day: 48, title: 'Week 7 Integration', week: 7, theme: 'Consolidation & Gratitude', duration: '20 minutes',
    teaching: "Seven weeks in. You have walked a path that most people never walk.\n\nThis week you learned to carry the inner eye into the marketplace and the kitchen. You practised the sacred art of deep listening. You explored the liminal spaces between dreaming and waking. You faced the ethics of power and perception. You honoured your body as the temple it is. You sat in extended darkness and met what lives there.\n\nThe mystic in the marketplace is no longer an aspiration. It is beginning to be a description of you.\n\nOne more week remains. Week 8 is about completion, vision, and carrying this forward into the rest of your life. But first, pause here. Let the work settle. Let gratitude do its quiet, transformative work.",
    practice: "Part 1 \u2014 Review (10 min): Read your journal entries from Days 42-47. What thread connects them? What are you noticing about who you are becoming?\n\nPart 2 \u2014 Gratitude Ceremony (10 min):\n\nSit in your practice space. Light a candle. Close your eyes.\n\nBring gratitude to: your body, which has carried this entire journey. Your mind, which resisted and then surrendered. Your heart, which opened even when it was afraid. Your inner eye, which showed you what you needed to see. This community of fellow seekers. David, your guide. The ancestors who walked before you. The path itself.\n\nFeel gratitude not as a thought but as a physical sensation in your chest. Let it expand. Let it fill you. This feeling \u2014 this warmth, this fullness \u2014 is the energetic signature of an integrated spiritual life.\n\nBlow out the candle. Carry the warmth.",
    journalPrompt: "What are you most grateful for in this journey? Not what you think you should be grateful for \u2014 what you actually feel gratitude for, in your body, right now?",
  },
  // ══════ WEEK 8: THE ETERNAL FLAME ══════
  {
    day: 49, title: 'Your Personal Practice', week: 8, theme: 'Designing a Lifetime Spiritual Routine', duration: '35 minutes',
    teaching: "The cohort ends. The practice does not.\n\nEverything you have experienced in these eight weeks \u2014 every meditation, every activation, every clearing, every dream, every moment of genuine seeing \u2014 has value only insofar as it continues beyond the container of this programme. The real question is not what happened during the cohort. It is what happens after.\n\nThe most important thing you will do this week is design a personal daily practice that fits the actual shape of your life \u2014 not the idealised version of your life, but the real one, with its responsibilities, its constraints, its interruptions, and its beauty.\n\nA sustainable practice has three qualities: it is short enough that you will actually do it every day, it is deep enough that it keeps the inner eye active and the channel clear, and it is flexible enough to adapt to the changing seasons of your life.\n\nThe ancient traditions did not prescribe one-size-fits-all practices. They worked with each individual\u2019s nature, their stage of development, their life circumstances, and their specific gifts. Your practice should be uniquely yours \u2014 drawn from the tools you have learned but arranged in the way that serves your particular path.",
    practice: "Part 1 \u2014 The Practice Audit (10 min):\n\nReview all the practices you have done in this cohort. In your journal, list every practice that genuinely resonated with you \u2014 the ones that produced real shifts, real clarity, real opening. Star the ones you would miss if they were gone.\n\nPart 2 \u2014 Designing Your Daily Practice (15 min):\n\nUsing your starred practices, design three versions of your daily practice:\n\nTHE MINIMUM (5-10 minutes): For busy days, travel days, difficult days. What is the absolute essential \u2014 the one practice that keeps the channel open no matter what? For most people this is: grounding (1 min) + conscious breathing (3 min) + Ajna activation (3 min) + brief journaling (2 min).\n\nTHE STANDARD (15-25 minutes): For most days. Your core routine. Grounding, protection, breathwork, Ajna activation, your primary channel practice, and journaling.\n\nTHE DEEP (45-60 minutes): For days when you have time and desire to go deep. The full practice including chakra work, extended meditation, dream work review, and creative expression.\n\nWrite all three versions in your journal. These are your practice maps going forward.\n\nPart 3 \u2014 The Sacred Commitment (5 min):\n\nChoose a specific time and place for your daily practice. Write: \u201CI commit to practising every day at [time] in [place]. On difficult days I will do The Minimum. On most days I will do The Standard. When I have space, I will do The Deep. I will not wait for motivation. I will show up regardless.\u201D\n\nSign it. This is the most important page in your journal.",
    journalPrompt: "What does your personalised daily practice look like? What time and place have you chosen? What is your Minimum, Standard, and Deep practice? What might threaten your consistency, and how will you protect against it?",
  },
  {
    day: 50, title: 'The Vision Quest', week: 8, theme: 'Seeing the Path Ahead', duration: '45 minutes',
    teaching: "In the indigenous traditions of North America, the vision quest is a rite of passage in which the seeker goes alone into the wilderness \u2014 fasting, praying, and sitting in stillness \u2014 to receive a vision of their life\u2019s direction from the Great Spirit.\n\nIn the African tradition, a similar practice exists: the sangoma-in-training enters a period of isolation and deep communion with the spirit world to receive the specific nature of their calling and the way they are meant to serve.\n\nYou do not need to go to the wilderness. The wilderness is within you. And the vision is waiting.\n\nToday we do the inner vision quest \u2014 an extended meditation designed to receive a clear vision of your path forward. Not the details. The direction. Not the how. The what. Not the timeline. The truth.\n\nThis is the inner eye\u2019s highest function: not seeing the past, not sensing the present, but perceiving the trajectory of your soul \u2014 the direction in which life itself is calling you to grow, serve, and become.",
    practice: "THE INNER VISION QUEST (45 minutes):\n\nPrepare your space with intention. This is one of the most important practices of the entire cohort. Candle. Incense if you use it. Silence. No interruptions.\n\nPhase 1 \u2014 Deep Grounding (10 min): Ground more deeply than you ever have. Roots not just into the earth but through the earth, into the molten core, into the very heart of the planet. Feel yourself held by something ancient and vast. You are safe. You are supported. You can afford to see the truth.\n\nPhase 2 \u2014 Full Activation (10 min): Move through all seven chakras from root to crown, activating each one briefly. Then rest at the Ajna. Indigo flame. Let it blaze. This is the eye that sees beyond time.\n\nPhase 3 \u2014 The Quest (20 min): With your inner eye fully active, ask: Show me my path. Show me the direction of my life from this point forward. Show me what I am here to do, to be, to offer.\n\nThen be completely silent and completely receptive. You are not creating a vision. You are receiving one.\n\nIt may come as an image \u2014 a landscape, a scene, a symbol. It may come as a feeling \u2014 a quality of energy that points in a direction. It may come as a knowing \u2014 a sudden certainty about the next chapter. It may come as a word or phrase. It may come as nothing \u2014 and then arrive in a dream tonight. All are valid.\n\nDo not judge what comes. Do not edit it. Do not decide whether it is realistic. Simply receive.\n\nPhase 4 \u2014 The Recording (5 min): Write everything. Every image, feeling, word, sensation. Draw if that serves better than words. This is the record of your vision. Return to it whenever you need to remember your direction.",
    journalPrompt: "What did you see? What did you feel? What direction is your life calling you toward? If you could summarise the vision in one sentence, what would it be?",
  },
  {
    day: 51, title: 'The Letter & The Legacy', week: 8, theme: 'Messages Across Time', duration: '35 minutes',
    teaching: "Tomorrow the cohort ends. Today we write across time.\n\nThe inner eye does not only perceive the present moment. It perceives patterns \u2014 the threads that connect past, present, and future into a single tapestry. From the vantage point of the awakened eye, your life is not a random sequence of events. It is a story with a direction, a purpose, and a meaning that becomes clearer the more you are willing to see.\n\nToday you write three letters.\n\nThe first is to the person you were 52 days ago \u2014 the one who sat down on Day 1 with nothing but an intention and a willingness to begin. You know things now that they could not have imagined. What would you tell them?\n\nThe second is to the person you will be one year from now. What do you want them to remember? What do you hope they have built from what you discovered here? What warning or encouragement do they need?\n\nThe third is to the world. Not the whole world \u2014 but to the people who will be touched by your awakening. Your family. Your community. Your students or clients or friends. The ones who will benefit from the fact that you chose to open your eyes. What does your awakened self wish to say to them?\n\nThese letters are not exercises. They are acts of spiritual power. When the inner eye speaks through written words with genuine intention, those words carry a charge that transcends the moment in which they were written. They become anchors \u2014 points of return that hold the vision steady when the storms of ordinary life try to blow it away.",
    practice: "Part 1 \u2014 Letter to Your Past Self (10 min):\n\nDear [your name] on Day 1...\n\nWrite what you wish you could have told yourself. The encouragement. The warnings. The things that surprised you. The things that were harder than expected and the things that were more beautiful than expected. Write with tenderness \u2014 that person was brave enough to begin without knowing where it would lead.\n\nPart 2 \u2014 Letter to Your Future Self (10 min):\n\nDear [your name] one year from now...\n\nWrite what you most want to remember. The vision you received. The commitments you made. The way it felt when the inner eye first showed you something true. The person you are becoming. Write as if this letter is a lifeline that your future self will desperately need on a day when they have forgotten why they started.\n\nPart 3 \u2014 Letter to the World (10 min):\n\nThis is the most important letter. It is the one that turns your awakening outward.\n\nWhat has the inner eye shown you that the world needs to hear? What truth have you discovered that you are willing to carry into your family, your community, your work? What is your message \u2014 not as a performance but as a genuine offering from someone who has seen something real?\n\nWrite it. Seal all three letters. Keep them somewhere sacred. Open the second one in exactly one year.",
    journalPrompt: "What was the hardest letter to write? What did you discover about yourself through the act of writing across time? What is the single most important thing the inner eye has shown you in this entire cohort?",
  },
  {
    day: 52, title: 'The Eternal Flame', week: 8, theme: 'Completion, Consecration & New Beginning', duration: '60 minutes',
    teaching: "Fifty-two days.\n\nYou began as a seeker. You end as a seer.\n\nNot a perfect seer. Not an infallible one. Not one who has all the answers or has transcended all human limitation. But a genuine one. A person who has done the work of opening the inner eye with sincerity, courage, and commitment. A person who can now perceive dimensions of reality that were invisible to them eight weeks ago. A person who has faced their shadows, cleared their channels, identified their gifts, and received a vision of their path.\n\nThis is no small thing. In the ancient world, what you have done would have been recognised as an initiation \u2014 a crossing from one state of being to another. You would have been received back into the community with ceremony, with honour, and with a new name that reflected who you had become.\n\nWe will do our own version of that today.\n\nBut first, understand this: completion is not ending. The flame that was lit on Day 1 \u2014 the flame of your intention, your willingness, your inner seeing \u2014 does not go out because the cohort is over. It is eternal. It was burning before you knew it existed. It will burn long after this moment passes.\n\nYour only task, from this day forward, is to tend it. To protect it from the winds of distraction, cynicism, and forgetfulness. To feed it with daily practice, honest living, and the courage to act on what you can now see. To share its warmth with others \u2014 not by preaching or performing, but by being the kind of person whose presence makes the room a little brighter, a little more honest, a little more alive.\n\nThe inner eye is not something you have. It is something you are. And you are ready.",
    practice: "THE COMPLETION CEREMONY (60 minutes):\n\nThis is the final practice of the cohort. Give it everything.\n\nPREPARATION: Create the most intentional version of your practice space you have ever created. Clean it. Arrange it. Light candles. Burn incense if you use it. Place your journal open to your Day 1 intention. Place photographs of your ancestors if you have them. This space is a temple tonight. You are the ceremony.\n\nTHE OPENING (5 min): Stand. Place your hand on your heart. Speak aloud: \u201CI have walked the path. I have done the work. I have opened my eyes. I am grateful for every step \u2014 the beautiful ones and the difficult ones. I honour the journey. I honour the one who walked it. I honour the flame that lit the way.\u201D\n\nTHE FULL PRACTICE (20 min): Perform your complete practice one final time as a cohort member. Grounding. Protection. Breathwork. Full chakra activation from root to crown. Ajna activation. AUM chanting. Extended silence at the third eye. Make it the deepest sitting of the entire 52 days. You know how. Your body knows. Trust it.\n\nTHE REVIEW (10 min): With eyes closed, allow the entire journey to pass before your inner eye. Day 1. The first time you felt something at the third eye point. The first vivid dream. The energy clearing that broke something open. The moment you identified your gift. The vision quest. The letters. All of it. Hold it all. Honour it all.\n\nTHE DECLARATION (5 min): Speak aloud your declaration \u2014 the final words of your cohort. Complete these sentences from the deepest place in you:\n\nI came to this journey seeking...\nI found...\nThe inner eye has shown me that I am...\nThe gift I carry forward is...\nI commit to...\nI am...\n\nTHE ETERNAL FLAME (5 min): Gaze at your candle flame. This flame represents the light of the inner eye \u2014 the light that was lit in you before you were born and will continue after you leave this world. It is the light of awareness itself. The light that sees without being seen. The light that knows without being told.\n\nAs you gaze at this flame, know that it is yours. No one gave it to you. No one can take it away. It does not depend on this cohort, this teacher, this community, or this moment. It is yours.\n\nBlow out the candle. Close your eyes. The flame is still there \u2014 burning in the darkness behind your eyelids, burning at the centre of your forehead, burning in the centre of your chest. It will always be there.\n\nOpen your eyes.\n\nYou are complete.\n\nTHE CLOSING (5 min): Sit in silence. Place both palms on the earth. Three breaths. Then stand. Step forward. The cohort is over. Your life as a seer has begun.\n\nWelcome home.",
    journalPrompt: "Write the final entry in your cohort journal. What did you come seeking? What did you find? Who are you now? And what will you do with the flame you carry?",
  },
]


function LoadingScreen() {
  return (
    <div style={{ minHeight:'100vh', display:'flex', alignItems:'center', justifyContent:'center', background:C.cream, fontFamily:sans }}>
      <div style={{ textAlign:'center' }}>
        <div style={{ fontSize:'3rem', marginBottom:'1rem' }}>🌿</div>
        <p style={{ color:C.muted }}>Loading your practice space...</p>
      </div>
    </div>
  )
}

function LockedScreen() {
  return (
    <div style={{ minHeight:'100vh', display:'flex', alignItems:'center', justifyContent:'center', background:C.cream, fontFamily:sans, padding:'2rem' }}>
      <div style={{ maxWidth:480, textAlign:'center', background:C.white, border:`1px solid ${C.border}`, borderRadius:16, padding:'3rem 2rem', boxShadow:'0 4px 24px rgba(0,0,0,0.06)' }}>
        <div style={{ fontSize:'3rem', marginBottom:'1rem' }}>🔒</div>
        <h2 style={{ fontFamily:serif, color:C.green, fontWeight:400, fontSize:'1.8rem', margin:'0 0 0.75rem' }}>Course Access Required</h2>
        <p style={{ color:C.muted, lineHeight:1.7, marginBottom:'2rem' }}>You need to enroll in a cohort to access the course content. Once payment is complete, David will activate your access within 24 hours.</p>
        <div style={{ display:'flex', flexDirection:'column', gap:'0.75rem' }}>
          <a href="/#pricing" style={{ display:'block', background:C.green, color:C.white, padding:'0.9rem', borderRadius:8, textDecoration:'none', fontWeight:500 }}>View Enrollment Options</a>
          <a href={`https://wa.me/27817904941?text=${encodeURIComponent('Hi David, I have completed payment and would like my course access activated.')}`} target="_blank" rel="noopener noreferrer" style={{ display:'block', background:'#25D366', color:C.white, padding:'0.9rem', borderRadius:8, textDecoration:'none', fontWeight:500 }}>💬 Message David on WhatsApp</a>
        </div>
      </div>
    </div>
  )
}

function CourseContent({ user }) {
  const { completed: completedDays, markDone, loading: progressLoading } = useProgress(user?.uid, 'week6-8')
  const [activeDay, setActiveDay] = useState(0)
  const days = completedDays || []

  const handleComplete = async (day) => { await markDone(day) }

  const currentDay = DAYS[activeDay]
  const progress = Math.round((days.length / 18) * 100)
  const wColor = weekColors[currentDay.week] || C.brown

  if (progressLoading) return <LoadingScreen />

  return (
    <>
      <Head>
        <title>Weeks 6-8: Integration & Embodiment — The Clarity Institute</title>
        <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,300;1,400&family=Jost:wght@300;400;500;600&display=swap" rel="stylesheet" />
      </Head>
      <div style={{ minHeight:'100vh', background:C.cream, fontFamily:sans }}>
        <nav style={{ background:C.white, borderBottom:`1px solid ${C.border}`, padding:'1rem 2rem', display:'flex', justifyContent:'space-between', alignItems:'center' }}>
          <Link href="/dashboard" style={{ fontFamily:serif, fontSize:'1.2rem', color:C.green, textDecoration:'none', fontWeight:600 }}>The Clarity Institute</Link>
          <div style={{ display:'flex', alignItems:'center', gap:'1rem' }}>
            <span style={{ fontSize:'0.82rem', color:C.muted }}>{progress}% complete</span>
            <Link href="/dashboard" style={{ fontSize:'0.85rem', color:C.muted, textDecoration:'none' }}>← Dashboard</Link>
          </div>
        </nav>

        <div style={{ maxWidth:1100, margin:'0 auto', padding:'2rem 1.5rem' }}>
          <div style={{ marginBottom:'2rem' }}>
            <span style={{ fontSize:'0.75rem', fontWeight:600, letterSpacing:'0.15em', textTransform:'uppercase', color:C.brown, display:'block', marginBottom:'0.5rem' }}>Weeks 6–8</span>
            <h1 style={{ fontFamily:serif, fontSize:'2.2rem', color:C.green, fontWeight:300, margin:'0 0 0.5rem' }}>Integration & <em style={{ color:C.brown }}>Embodiment</em></h1>
            <p style={{ color:C.muted, margin:0, fontSize:'0.95rem' }}>Ground your gifts into daily life, relationships, vocation, and your unique soul purpose.</p>
            <div style={{ background:C.cream2, borderRadius:999, height:8, overflow:'hidden', marginTop:'1rem', maxWidth:400 }}>
              <div style={{ height:'100%', width:`${progress}%`, background:C.brown, borderRadius:999, transition:'width 0.5s ease' }} />
            </div>
          </div>

          <div style={{ display:'grid', gridTemplateColumns:'280px 1fr', gap:'2rem' }}>
            <div>
              <div style={{ background:C.white, border:`1px solid ${C.border}`, borderRadius:14, overflow:'hidden', position:'sticky', top:'1rem' }}>
                {DAYS.map((d, i) => {
                  const isActive = i === activeDay
                  const isComplete = days.includes(d.day)
                  const isWeekBreak = i === 0 || d.week !== DAYS[i-1]?.week
                  const wc = weekColors[d.week] || C.brown
                  return (
                    <div key={d.day}>
                      {isWeekBreak && (
                        <div style={{ padding:'0.6rem 1rem', background:wc, fontSize:'0.72rem', fontWeight:600, color:C.white, textTransform:'uppercase', letterSpacing:'0.1em' }}>Week {d.week}</div>
                      )}
                      <button onClick={() => { setActiveDay(i); window.scrollTo(0,0) }} style={{
                        display:'flex', alignItems:'center', gap:'0.6rem', width:'100%', textAlign:'left', padding:'0.7rem 1rem',
                        background: isActive ? `${wc}10` : 'transparent', border:'none', borderBottom:`1px solid ${C.border}`,
                        borderLeft: isActive ? `3px solid ${wc}` : '3px solid transparent',
                        cursor:'pointer', fontFamily:sans, fontSize:'0.85rem', color: isActive ? wc : C.text, fontWeight: isActive ? 500 : 400,
                      }}>
                        <span style={{
                          width:22, height:22, borderRadius:'50%', display:'flex', alignItems:'center', justifyContent:'center',
                          fontSize:'0.7rem', fontWeight:600, flexShrink:0,
                          background: isComplete ? wc : C.cream, color: isComplete ? C.white : C.muted,
                          border: isComplete ? 'none' : `1px solid ${C.border}`,
                        }}>{isComplete ? '✓' : d.day}</span>
                        <span style={{ lineHeight:1.3 }}>{d.title}</span>
                      </button>
                    </div>
                  )
                })}
              </div>
            </div>

            <div>
              <div style={{ background:C.white, border:`1px solid ${C.border}`, borderRadius:16, padding:'2.5rem', marginBottom:'1.5rem' }}>
                <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:'1.5rem', flexWrap:'wrap', gap:'0.5rem' }}>
                  <div>
                    <span style={{ fontSize:'0.75rem', color:wColor, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.1em' }}>Day {currentDay.day} · {currentDay.theme}</span>
                    <h2 style={{ fontFamily:serif, fontSize:'2rem', color:C.green, fontWeight:300, margin:'0.25rem 0 0' }}>{currentDay.title}</h2>
                  </div>
                  <span style={{ fontSize:'0.8rem', color:C.muted, background:C.cream, padding:'0.3rem 0.75rem', borderRadius:999 }}>⏱ {currentDay.duration}</span>
                </div>

                <div style={{ marginBottom:'2rem' }}>
                  <h3 style={{ fontSize:'0.8rem', fontWeight:600, color:C.brown, textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:'0.75rem' }}>Today's Teaching</h3>
                  {currentDay.teaching.split('\n\n').map((para, i) => (
                    <p key={i} style={{ color:C.text, fontSize:'0.95rem', lineHeight:1.85, margin:'0 0 1rem' }}>{para}</p>
                  ))}
                </div>

                <div style={{ background:`linear-gradient(135deg, #f0f4f0, ${C.cream})`, border:`1px solid ${C.green}25`, borderRadius:14, padding:'1.75rem', marginBottom:'2rem' }}>
                  <h3 style={{ fontSize:'0.8rem', fontWeight:600, color:C.green, textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:'0.75rem' }}>🧘 Today's Practice</h3>
                  {currentDay.practice.split('\n\n').map((para, i) => (
                    <p key={i} style={{ color:C.text, fontSize:'0.95rem', lineHeight:1.85, margin:'0 0 1rem' }}>{para}</p>
                  ))}
                </div>

                <div style={{ background:C.cream, borderLeft:`3px solid ${C.orange}`, borderRadius:'0 10px 10px 0', padding:'1.25rem 1.5rem', marginBottom:'2rem' }}>
                  <h3 style={{ fontSize:'0.8rem', fontWeight:600, color:C.orange, textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:'0.5rem' }}>📝 Journal Prompt</h3>
                  {currentDay.journalPrompt.split('\n\n').map((para, i) => (
                    <p key={i} style={{ color:C.text, fontSize:'0.95rem', lineHeight:1.75, margin:'0 0 0.5rem', fontStyle:'italic' }}>{para}</p>
                  ))}
                </div>

                <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', flexWrap:'wrap', gap:'1rem' }}>
                  <button onClick={() => handleComplete(currentDay.day)} disabled={days.includes(currentDay.day)} style={{
                    background: days.includes(currentDay.day) ? C.cream : wColor,
                    color: days.includes(currentDay.day) ? wColor : C.white,
                    border: days.includes(currentDay.day) ? `1.5px solid ${wColor}` : 'none',
                    padding:'0.85rem 2rem', borderRadius:8, fontFamily:sans, fontSize:'0.95rem', fontWeight:500,
                    cursor: days.includes(currentDay.day) ? 'default' : 'pointer',
                  }}>{days.includes(currentDay.day) ? '✓ Day Completed' : 'Mark Day as Complete'}</button>

                  <div style={{ display:'flex', gap:'0.5rem' }}>
                    {activeDay > 0 && (
                      <button onClick={() => { setActiveDay(activeDay - 1); window.scrollTo(0,0) }} style={{
                        background:'transparent', color:C.muted, border:`1px solid ${C.border}`,
                        padding:'0.7rem 1.25rem', borderRadius:8, fontFamily:sans, fontSize:'0.85rem', cursor:'pointer',
                      }}>← Previous</button>
                    )}
                    {activeDay < DAYS.length - 1 && (
                      <button onClick={() => { setActiveDay(activeDay + 1); window.scrollTo(0,0) }} style={{
                        background:wColor, color:C.white, border:'none',
                        padding:'0.7rem 1.25rem', borderRadius:8, fontFamily:sans, fontSize:'0.85rem', cursor:'pointer',
                      }}>Next Day →</button>
                    )}
                    {activeDay === DAYS.length - 1 && (
                      <Link href="/dashboard" style={{
                        background:C.green, color:C.white, padding:'0.7rem 1.25rem',
                        borderRadius:8, textDecoration:'none', fontSize:'0.85rem', fontWeight:500,
                      }}>🎉 Complete Course — Return to Dashboard</Link>
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default function Week6_8() {
  const { user, loading, isPaid, isAdmin } = useAuth()
  const router = useRouter()
  useEffect(() => {
    if (!loading && !user) router.replace('/login?redirect=/week6-8')
  }, [loading, user, router])
  if (loading) return <LoadingScreen />
  if (!user) return <LoadingScreen />
  if (!isPaid && !isAdmin) return <LockedScreen />
  return <CourseContent user={user} />
}
